Linaro/test-definitions

- automated/lib/android-test-lib
after ran the wifi join command to avoid the effect
on test result like reported here:
https://bugs.linaro.org/show_bug.cgi?id=4236
Change-Id: I15e9710635beddc964456e18e06e8a361d5fae78
> android-test-lib adb_join_wifi: uninstall the package

- automated/linux/ltp/skipfile-lkft.yaml
sendfile09 and sendfile09_64 tests creates 5GB file and calls
sendfile(2) with offset at 3GB. These tests are time consuming so skipping
on slow devices db410c and hikey.
Change-Id: I9a215e1fd531dd31f1ffa5acc1a28485dd19dcec
> LTP: sendfile09: skip creating large files

- automated/lib/android-test-lib
uninstall that package would cause wifi disconnected
as reported here:
https://projects.linaro.org/browse/LSS-402
This reverts commit 1136333f3659ab251096848444d94ae7e478d31a.
> Revert "android-test-lib adb_join_wifi: uninstall the package"

- automated/android/noninteractive-tradefed/tradefed.yaml
- automated/android/tradefed/tradefed.yaml
Make sure that comparison is case insensitive to catch any possible
reboot in LAVA. Also align the comparison condition between different
tradefed implementations.
> android/tradefed: improve reboot variable comparison

- automated/linux/ltp/skipfile-lkft.yaml
The test cases known to failed are moved from skipfile-lkft.yaml to
qa known issues report repository ltp-production.yaml file.
The fixed test cases entries removed from skipfile-lkft.yaml file.
> LTP: moved skip list to qa known issues list

- automated/android/noninteractive-tradefed/tradefed.yaml
reported like following:
/lava-610173/1/tests/1_cts-focused2-armeabi-v7a/run.sh: 35: /lava-610173/1/tests/1_cts-focused2-armeabi-v7a/run.sh: Bad substitution
but not sure why this problem only happens for x15 jobs,
jobs for hikey builds could work without problem
Change-Id: I4dbaf0670f82bec69e2146d8cf91974feaf86dc1
> noninteractive-tradefed: use grep to workaround Bad substitution  problem

- automated/android/multinode/connect-to-remote-adb-tcpip-devices.yaml
- automated/android/multinode/release-remote-adb-tcpip-devices.yaml
- automated/android/multinode/remote-adb-devices-smoke-test.yaml
- automated/android/multinode/share-local-device-over-adb-tcpip.yaml
- automated/android/multinode/tradefed/example-job-template-cts.yaml
- automated/android/multinode/tradefed/sts_util.py
- automated/android/multinode/tradefed/tradefed-multinode.sh
- automated/android/multinode/tradefed/tradefed-multinode.yaml
- automated/android/multinode/tradefed/tradefed-runner-multinode.py
- automated/android/multinode/tradefed/utils.py
- automated/android/multinode/wait-and-keep-local-device-accessible.yaml
- automated/android/multinode/wait-for-release-and-reset.yaml
- automated/lib/android-multinode-test-lib
- automated/lib/android_adb_wrapper.py
- automated/lib/android_ui_wifi.py
Continuation of changes previously discussed on Gerrit: [tradefed_shards_with_retry](https://review.linaro.org/#/q/topic:tradefed_shards_with_retry+(status:open+OR+status:merged))
> Add MultiNode TradeFed tests for --shards and with session retry

- automated/linux/ltp/skipfile-lkft.yaml
From KV-171 investigation LTP dio long running tests have been
identified and skipping those test cases on all devices.
Ref:
https://projects.linaro.org/browse/KV-171
> LTP: skip LTP dio long running tests on all devices

- automated/linux/ltp/skipfile-lkft.yaml
LTP dio tests getting timedout on db410c device so skipping most of
them on db410c.
Ref:
https://projects.linaro.org/browse/KV-171
> LTP: skipping dio test runs on slow running db410c

- automated/linux/ssuite/run-bench.sh
- automated/linux/ssuite/ssuite-bench.yaml
The S suite is a small collection of benchmarks for storage I/O.
For the moment, this test makes it possible to execute the following
two benchmarks with the suite:
- responsiveness, by measuring start-up times of real applications
under real background workloads;
- throughput with processes doing filesystem or raw I/O in parallel
(figure of merit measured by many other suites too).
Signed-off-by: Paolo Valente <paolo.valente@linaro.org>
> automated: linux: add the ssuite benchmark collection

- automated/linux/kselftest/skipfile-lkft.yaml
Kernel panic while running bpf: test_tunnel.sh on linux -next and mainline
This is been reported upstream and waiting for the fix.
till it get fixed this test case test_tunnel.sh will be skipped on all devices
and all branches
Ref:
https://bugs.linaro.org/show_bug.cgi?id=4307
> kselftest: skip kernel crash test case test_tunnel.sh on all devices

- automated/lib/sh-test-lib
Shell test library have report_pass() and report_fail()
Here report_skip() also needed so this patch adding it.
> automated/lib/sh-test-lib: Adding report_skip api

- .travis.yml
- validate.py
* Use libmagic to detect file type so that we don't have to update the
file for new files without extension.
* Because test plan and lava test job definition yaml file also contain
'metadata' key, use 'run' key to determine test definition yaml file.
* Skip sanity check on unknown file types.
> sanity-check: improve file type determination

- automated/lib/android-test-lib
to resolve the problem reported here:
https://bugs.linaro.org/show_bug.cgi?id=4236
as there is a problem to fix the cached apk in lab
as mentioned here[1], we changed to use new file name
to workaround.
[1]: https://projects.linaro.org/browse/LSS-432?focusedCommentId=76245&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-76245
Tested with following jobs:
https://validation.linaro.org/scheduler/job/1909008 -- aosp master builds
https://validation.linaro.org/scheduler/job/1909009 -- lcr pie build
https://validation.linaro.org/scheduler/job/1909010 -- oreo build
https://lkft.validation.linaro.org/scheduler/job/641823 -- lcr pie build on lkft
Change-Id: Ibc51a802117cecfe1d15b288bac9b55f6e0feec4
> adb_join_wifi: use new non-debugable apk

- automated/linux/kselftest/kselftest.sh
Not all versions of tar automatically detect compressed archives (eg.
BusyBox v1.22.1 version of tar). Hence the [z] option needs to be
specified in order to successfully untar a gunzip archive in these cases.
> kselftests: fix tar magic

- automated/linux/perf/perf.sh
- automated/linux/perf/perf.yaml
Perf is a profiler tool for Linux and is used to collect and analyze
performance and trace data.
This test runs following perf commands:
- record(record events for later reporting)
- report(break down events by process, function, etc)
- stat(obtain event counts)
- test(Run sanity tests)
Upstream link,
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/perf/Documentation/perf.txt
Ref:
Test perf in LKFT
https://projects.linaro.org/browse/KV-195
> linux/perf: Adding perf test case for LKFT test plan

- validate.py
When shebang line is incorrect, python-magic returns file type as
plain/text, then sanity check will be skipped. This patch treat all
files end with .sh as shell script and do force shellcheck test.
> validate.py: force check all files end with .sh

- automated/linux/ssuite/run-bench.sh
- automated/linux/ssuite/ssuite-bench.yaml
This commit makes the ssuite produce a result file and send it to
lava. For each passed test case, the average value of the main
quantity measured is reported. Here is the format of possible lines in
the result file:
throughput-<scheduler1_name>--<workload_name> pass <real number> MB/s
throughput--<workload1_name>--<scheduler1_name> fail
<app_name>-startup--<workload_name>--<scheduler1_name> pass <real number> sec
<app_name>-startup--<workload_name>--<scheduler1_name> fail
Signed-off-by: Paolo Valente <paolo.valente@linaro.org>
> automated, linux, ssuite: produce result file

- automated/android/microbenchmarks/manifest.xml
To use Google's ART buildbot scripts, we need to at least be able to
source the AOSP environment.
This results in a longer sync, but still reasonable (less than
45s).
> ART: add few repos in manifest

- automated/linux/v4l2/v4l2-compliance.sh
Replacing string "/" with "-" for better results format for test case names.
Test case names:
old VIDIOC_G/S_TUNER/ENUM_FREQ_BANDS
new VIDIOC_G-S_TUNER-ENUM_FREQ_BANDS
> v4l2: fix results parsing

- automated/linux/memtester/memtester.sh
Add a failure point if memtester isn't installed in the rootfs
Change-Id: Icc149f03689318b9ca75a67e57b3d5bd298e31db
> memtester: add existence check

- automated/android/boottime/boottime.sh
instead of in the middle of the test,
especially not after any adb commands
To make sure the "device not found" problem after reboot, like reported here:
https://lkft.validation.linaro.org/scheduler/job/688517#L5047
was not caused by the installation of this packages like usbutils
Change-Id: I3cadf14714ea9e69b5a1493597ac9be4e3bd444c
> boottime: run install_deps at the beginning of the script

- automated/linux/kvm-unit-tests/kvm-unit-tests.sh
- automated/linux/kvm-unit-tests/kvm-unit-tests.yaml
kvm unit tests skipped on juno-r2 due to big.LITTLE cpu architecture.
when task migrating from big to small or vice versa tests getting skipped.
To avoid task migration on heterogeneous cpu clusters on juno-r2 devices
here we are setting CPU affinity to primary CPU 0 and run tests.
by using an extra parameter SMP.
If $SMP="false" then enforce it run with taskset
taskset -c 0 ./run_tests.sh
else
./run_tests.sh
> kvm-unit-tests.sh: set CPU affinity to CPU 0 for run_tests.sh

- automated/linux/memtester/memtester.sh
Because memtester.sh runs with "-e", the existence check was causing the
script to exit without reporting a failure, if the command didn't exist.
Run "set +e" to allow "command -v memtester" to fail with an error code,
then "set -e" again afterwards.
> memtester: fix existence check

- automated/lib/android-test-lib
> automated/android: bail in case adb root times out

- automated/linux/igt/igt-chamelium-test.sh
Sometimes git clone fails and shows "The remote end hung up unexpectedly."
Raising the postBuffer size to workaround it.
Gernerate igt-gpu-tools HTML test report.
> igt: fix git clone error and generate HTML test report

- automated/linux/docker-integration-test/local-daemon.sh
SKIP_INSTALL is set to True/true or False/false, so a simple check,
like:
if "${SKIP_INSTALL}"; then
will fail if the string isn't all lower case, because the string is
executed as a command. Both true and false are valid commands, whereas
True and False are not.
Once the check fails, then false is selected, so it will attempt to
install, causing problems on systems where installation isn't supported,
even when the dependencies are pre-installed.
The check also fails on LAVA when the definition is passing lower case
true/false, because LAVA always passes True/False in mixed case.
> local-daemon: fix SKIP_INSTALL

- automated/linux/network-basic/network-basic.sh
- automated/linux/network-basic/network-basic.yaml
network-basic: skip set interface down on NFS mounted fs
x86 running network basic test failed to make clean exit because
test case set network interface down and NFS lost connection. so
NFS parameter introduced to skip "set interface down" command when
NFS is true.
+ echo 'ip-link-interface-down pass'
[  241.270557] nfs: server 10.66.16.116 not responding, still trying
[  241.270569] nfs: server 10.66.16.116 not responding, still trying
ref:
https://lkft.validation.linaro.org/scheduler/job/735083#L1575
> network-basic: skip set interface down on NFS mounted fs

- automated/linux/igt/igt-chamelium-test.sh
Change FrameDumpPath to /root/dump-frames
> igt: Change FrameDumpPath

- automated/linux/igt/igt-chamelium-test.yaml
dump-igt-chamelium-test-result.yaml is used for dumping igt test result
and upload artifact to Artifactorial
> igt: add dump-igt-chamelium-test-result.yaml

- automated/linux/kselftest/skipfile-lkft.yaml
Updating kselftest skiplist for hangs test cases on linux next and mainline.
And when kselftest version update to 5.1 on stable branches
there is a hang for arm64 on 4.19 kernel branch due to test_progs
test_progs has to cherry-picked in to 2019.05
or 
create a new tag 2019.06 = 2019.05 + one patch [ 2c294af7cf ( kselftest: skip hang test case test_progs on 4.19 branch ) ]
> kselftest skiplist update

- automated/linux/ltp/skipfile-lkft.yaml
Add Schneider RZN1D board into skipfile-lkft.yaml to skip test cases
that are skipped for dragonboard-410c board.
Signed-off-by: Shawn Guo <shawn.guo@linaro.org>
> ltp: add Schneider RZN1D board into skipfile-lkft.yaml

- automated/linux/ltp/ltp.sh
The unprivileged_userns_clone procfs entry exists only with distro
kernel with particular patch applied, e.g. the patch [1] with debian
kernel.  On development boards which mostly run upstream kernel without
such patch, the ltp script will give following message which looks like
something goes wrong.
++ sysctl -n kernel.unprivileged_userns_clone
sysctl: cannot stat /proc/sys/kernel/unprivileged_userns_clone: No such file or directory
+ '[' '' -eq 0 ']'
./ltp.sh: line 157: [: : integer expression expected
Let's check unprivileged_userns_clone existence first before accessing
it, so that we can avoid above "error" messages and the confusion caused
by it.
[1] https://salsa.debian.org/kernel-team/linux/blob/master/debian/patches/debian/add-sysctl-to-disallow-unprivileged-CLONE_NEWUSER-by-defau …
> ltp: check unprivileged_userns_clone existence first

- automated/linux/igt/igt-chamelium-test.yaml
- automated/linux/igt/print-test-result.py
Due to html2text is quite old and the code hasn't been updated since 2005, it might be concerned to be included in the image.
Since igt-gpu-tools will generate a plain text test result and save it with JSON format.
I created a python script to print it in LAVA test log.
With this approach, html2text will not be needed.
> igt: print igt test result with python script

- automated/android/noninteractive-tradefed/monitor_fastboot.sh
to work around problems like reported here:
nice lxc-attach -n lxc-test-1919582 -- fastboot -s 28146262003EFFEE flash boot /lava-lxc/lkft-hikey-android-9.0-mainline-boot.img
Thu Jun 20 08:45:49 UTC 2019
+ fastboot boot /lava-lxc/boot*.img
fastboot: error: cannot load '/lava-lxc/boot*.img': No such file or directory
+ sleep 30
https://validation.linaro.org/scheduler/job/1919582#L5627
Change-Id: Ie4e45e22ef203ea0c519979a2b411328ca3ccce9
> tradefed monitor_fastboot.sh: support more boot image names

- automated/android/noninteractive-tradefed/setup.sh
- automated/android/noninteractive-tradefed/tradefed.sh
- automated/android/noninteractive-tradefed/tradefed.yaml
- automated/android/tradefed/setup.sh
- automated/android/tradefed/tradefed.sh
- automated/android/tradefed/tradefed.yaml
1. the _JAVA_OPTIONS confuses the java version check in cts/vts
and as cts/vts try to allocate more memory in their scripts following:
https://android.googlesource.com/platform/test/vts/+/refs/heads/master/tools/vts-tradefed/etc/vts-tradefed#187
https://android.googlesource.com/platform/test/suite_harness/+/refs/heads/master/tools/cts-tradefed/etc/cts-tradefed#133
there is no meaning to set _JAVA_OPTIONS any more.
2. fixed to use jdk8 for vts/cts test
as the installed openjdk-9-jdk-headless would cause following error with vts test:
Using commandline arguments as starting command: [run, commandAndExit, vts-kernel, --module, VtsKernelLinuxKselftest]
java.lang.reflect.InaccessibleObjectException: Unable to make member of class sun.reflect.annotation.AnnotationInvocationHandler accessible: …
> noninteractive-tradefed: use jdk8 and remove _JAVA_OPTIONS

- automated/linux/hci-smoke/hci-smoke-test.sh
This change improves the hci smoke test slightly by testing scan and inquiry commands. It also checks to make sure available devices show up in the listing.
We may want to pass a param to the test telling it if there are actual devices around the tested hardware.
This is the output from a test run:
Testing output from running hci-smoke-test.sh:
INFO: About to run HCI smoke test...
INFO: Output directory: /home/user/automated/linux/hci-smoke/output
INFO: Running hciconfig test...
hci0:	Type: Primary  Bus: USB
BD Address: AC:ED:5C:44:A2:31  ACL MTU: 1021:4  SCO MTU: 96:6
UP RUNNING PSCAN 
RX bytes:103593611 acl:1117 sco:0 events:14794579 errors:0
TX bytes:-246215823 acl:14791514 sco:0 commands:2734 errors:0
hciconfig pass
INFO: Running hciconfig_boot test...
UP RUNNING PSCAN …
> Add hci scanning and inquiry to the hci smoke tests

- automated/linux/kernel-config-checker/kernel-config-checker.sh
- automated/linux/kernel-config-checker/kernel-config-checker.yaml
Add new test to check the kernel config file for the presence of multiple
CONFIG_* values.
* kernel-config-checker.sh: New kernel config file checker script.
* kernel-config-checker.yaml: New kernel config file checker test.
Signed-off-by: Luis Machado <luis.machado@linaro.org>
> New kernel config file checker

- automated/android/ion-monitor-tool/example-job.yaml
- automated/android/ion-monitor-tool/ion-monitor-tool.yaml
- automated/android/ion-monitor-tool/runner.sh
- automated/android/ion-monitor-tool/setup.sh
Also added an example test job for LAVA.
This tool comes from MMWG team, to help monitoring memory leaks with ION heaps.
Signed-off-by: Axel Le Bourhis <axel.lebourhis@nxp.com>
> Added test definition to drive ion-monitor-tool for Android.

- automated/linux/sysfs-bus-iio-smoke/sysfs-bus-iio-smoke.sh
- automated/linux/sysfs-bus-iio-smoke/sysfs-bus-iio-smoke.yaml
The sysfs bus iio smoke test checks if specific sysfs-bus-iio
properties are within sane bounds, like, for example, temperature or voltage
data.
These tests can be augmented in the future to include string-based property values as opposed to numberic values.
This is a test that was available internally that i've revamped and wanted to make available upstream in case more people find it useful.
Signed-off-by: Luis Machado <luis.machado@linaro.org>
> New sysfs bus iio smoke test

- automated/linux/kselftest/skipfile-lkft.yaml
https://bugs.linaro.org/show_bug.cgi?id=5332
> kselftest: lkft: add proc-pid-vm to skipfile

- automated/linux/kvm-unit-tests/kvm-unit-tests.sh
- automated/linux/kvm-unit-tests/kvm-unit-tests.yaml
Adding git reference parameter for kvm unit tests to git checkout on
given git reference like branch/tag/commit-id
> kvm-unit-tests: Adding git reference parameter

- automated/linux/kselftest/skipfile-lkft.yaml
Adding net/udpgro.sh to the skip file on next for i386.
https://bugs.linaro.org/show_bug.cgi?id=4078
> kselftest: lkft: add udpgro.sh to skipfile

- automated/linux/kselftest/skipfile-lkft.yaml
These three test are skipped
- nft_nat.sh
- conntrack_icmp_related.sh
- rtnetlink.sh
> kselftests: Adding hang tests case to skiplist

- automated/linux/kselftest/skipfile-lkft.yaml
> kselftests: x86 instead of x86_64 for skipgen

- automated/linux/kselftest/skipfile-lkft.yaml
The following netfilter test cases hangs intermittently,
- nft_trans_stress.sh
- bridge_brouter.sh
- nft_flowtable.sh
ref:
https://bugs.linaro.org/show_bug.cgi?id=5341
> kselftest: skip netfilter tests

- automated/linux/kselftest/skipfile-lkft.yaml
net: xfrm_policy.sh hangs on i386 running on next
https://bugs.linaro.org/show_bug.cgi?id=5342
> kselftest: lkft: add xfrm_policy.sh to skipfile

- automated/android/boottime/boottime.sh
as the launcher activity log is not printed in the logcat any more
Change-Id: Ia757ca5c9e9a7a63023e6ba6d55e3e6534d24b88
> android boottime: use wait_boot_completed instead of wait_homescreen

- automated/linux/docker-integration-test/local-daemon.sh
The docker-ce repo is clones to provide access to the files, not the
history in the repo.
Using '--depth 1' will speed up the clone and also uses less memory:
useful on resource constrained systems.
When making a shallow clone, you also want to specify the branch/tag you
require, because it most likely will not be available after the clone
completes.
> docker: git clone depth 1

- automated/linux/docker/docker.sh
Add support for running the "hello-world" sample image to the docker
test.
This image requires fewer resources than an ubuntu system running a
shell command.
To run hello-world, the caller passes in "hello-world" for the IMAGE
parameter.
> docker: hello-world support

- automated/android/microbenchmarks/microbenchmarks.sh
The script now autodetects the device, and could result in using
binaries in a non-existing location.
> uBenchmarks: provide target-device manually

- automated/linux/kselftest/skipfile-lkft.yaml
Adding 5.3 stable rc branch to skipfile to skip ftracetest.
> kselftest: updating 5.3 branch for skipfile

- automated/android/apk-automation/apk-automation.sh
- automated/android/apk-automation/common/__init__.py
New version of matplotlib requires python3. This patch makes sure that
python2 version of matplotlib is installed
> automated/android: fix apk-automation installation error

- automated/linux/perf/perf.sh
The perf test results parser is updated.
Results count increased from 5 to 77.
> perf: Adding perf test results parser

- automated/linux/igt/igt-chamelium-test.yaml
Now we already have LAVA support allowing test shell to query device
dictionary. So the DUT can get the paired Chamelium IP address from
shell environment variable ${CHAMELIUM_STATIC_IP}
> igt: get Chamelium IP address from shell environment variable

- automated/linux/ltp-open-posix/ltp-open-posix.sh
Open Posix test suite may report test result as UNRESOLVED. This might
mean ABI break and should be classified as FAIL in test-definitions
convention.
> automated/linux: classify UNRESOLVED as fail

- automated/linux/workload-automation/workload-automation.sh
- automated/linux/workload-automation/workload-automation.yaml
It is causing problems because new pip versions (10.x) has a bug when
dealing with distutil packages. [1]
[1] https://github.com/pypa/pip/issues/5247
Change-Id: Ifdd9322dc507907b6347d26478a04a890dec6fed
> automated/linux/workload-automation: Add ability to skip upgrade pip

- automated/linux/workload-automation/workload-automation.yaml
We have a workload-automation3 testdef so this one is target to use
the version 2 of the tool use proper tags by default.
Change-Id: I9121a14772fe59d750c68d97c59fb2f3ab481004
> automated/linux: Use tags for 2.x in workload-automation

- automated/linux/ssuite/run-bench.sh
Adding ssuite-testcase-name-<max/min/avg/std> pass measurements units in sec
ref:
LAVA job running ssuite 144 results
https://lkft.validation.linaro.org/results/978203/1_ssuite?search=&length=200#table
> ssuite: Fix results parser

- automated/android/noninteractive-tradefed/setup.sh
- automated/android/noninteractive-tradefed/tradefed.yaml
- automated/android/tradefed/setup.sh
- automated/android/tradefed/tradefed.yaml
for different android version cts/vts test.
Now only aosp master version needs to use openjdk-11,
other older versions need to use openjdk8
> tradefed and noninteractive-tradefed: install different openjdk version

- automated/linux/kselftest/skipfile-lkft.yaml
selftests net rtnetlink.sh test hangs intermittently on all devices and which
is blocking other tests to run. So skipping rtnetlink.sh tests.
ref:
https://bugs.linaro.org/show_bug.cgi?id=5339
> kselftests: skip rtnetlink.sh on all devices

- automated/linux/kvm-unit-tests/kvm-unit-tests.sh
As per the kvm unit tests author it is recommended to run tests
with option -a to enable and run all tests.
> kvm-unit-tests: run all test with option a

- automated/linux/igt/control_chamelium.sh
- automated/linux/igt/igt-test.yaml
1. Power cycle the Chamelium once we don't get the ping response from it
(snmpset from Net-SNMP is required)
2. Check uboot console lock status and uptime of the Chamelium
3. Delete chameliumd log after each test
> igt: power cycle Chamelium once it is unreachable

- automated/linux/smoke/smoke.sh
This allows the test commands to contain '/' characters, eg:
./smoke.sh -t "cat /proc/cpuinfo"
> smoke.sh: use # as sed delimiter

- automated/linux/iperf/iperf-client.yaml
- automated/linux/iperf/iperf-server.yaml
- automated/linux/iperf/iperf.sh
- automated/linux/iperf/lava-multinode-job-example-iperf.yaml
Split the iperf.sh script so it runs as either server of client, but not
both.
If the caller wishes to run the test with a local server, they must
invoke the script twice.
This commit also creates a YAML for the server.
Additional parameters are added to the client to allow CPU affinity, or
to reverse the test, so the client is the receiver instead of the
transmitter.
> iperf: split into client and server

- automated/linux/armnn-benchmarks/armnn-benchmarking.yaml
armnn-benchmarking-build: updating LINK_SNAPSHOT file path to point to armnn-full.tar.xz
> Updating armnn-benchmarking.yaml

- automated/linux/iperf/iperf-client.yaml
- automated/linux/iperf/iperf-server.yaml
- automated/linux/iperf/iperf.sh
- automated/linux/iperf/lava-multinode-job-example-iperf.yaml
Rather than run the LAVA commands in the YAML, run them in the script.
This is particularly useful so that installation happens before the lava-wait.
This helps prevent timeouts on slower platforms.
> iperf: move lava commands into iperf.sh

- mkdocs.yml
- mkdocs_plugin/requirements.txt
- mkdocs_plugin/setup.py
- mkdocs_plugin/testdefinitionsmkdocs/__init__.py
This patch will add 'tags' top nav bar item to the mkdocs page. The tags
are collected from the metadata 'scope' list in each test.
> docs: add tags

- automated/linux/block-device/block-device.sh
- automated/linux/block-device/block-device.yaml
Test a partition on a block device.
Check that files can be written and read reliably, measure the timings
for read and write, and run the bonnie++ block device test on the
device.
> block-device test added

- automated/linux/igt/igt-test.sh
- automated/linux/igt/igt-test.yaml
igt-gpu-tools could run tests other than Chamelium test.
If we run a given test list, we don't need to check Chamelium status.
> igt: skip Chamelium test when running a given test list

- automated/linux/kselftest/skipfile-lkft.yaml
> kselftest: skip ftracetest on stable-rc branches 5.4, 5.6 and 5.7

- automated/utils/test-runner.py
After migration to python3 pexpect started failing on remote tests. This
can be fixed by moving to 'spawnu' so all input is considered utf-8
> test-runner: change pexpect.spawn to spawnu

- automated/linux/ssuite/run-bench.sh
- automated/linux/ssuite/ssuite-bench.yaml
Milosz reported that benchmarks last for too long. This change
should reduce benchmark duration significantly.
Signed-off-by: Paolo Valente <paolo.valente@linaro.org>
> ssuite: limit startup-time benchmarks to gnome-terminal

- automated/android/noninteractive-tradefed/tradefed-runner.py
- automated/android/noninteractive-tradefed/tradefed.yaml
- automated/android/tradefed/result_parser.py
1. fixed the problem that not all xml un-support characters removed.
2. continue to try to upload the result/log files to archive site even the tradefed test itself failed.
Test job which get the result successfully:
https://validation.linaro.org/scheduler/job/2048126
The old jobs:
https://validation.linaro.org/scheduler/job/2045998 failed to get the result successfully
https://validation.linaro.org/scheduler/job/2045733 not have the attachment uploaded
> Some improvement on the tradefed  test

- automated/linux/24h-stress-test/24h-stress-test.sh
The test is validated: https://validation.linaro.org/scheduler/job/2052741
Signed-off-by: Vishal Bhoj <vishal.bhoj@linaro.org>
> 24h-stress-test: remove libgcrypt11-dev dependency

- plans/testplan2html.py
Fixes the following warning when calling yaml.load
testplan2html.py:243: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
> yaml.load fix

- automated/linux/kselftest/kselftest.sh
Lots of kselftests depend on the 'ip' tool.
> kselftest: add ip to install_deps

- automated/linux/kselftest/kselftest.sh
The kselftest.sh wrapper currently assumes that the kselftest tarball
was created with a top-level "kselftest" directory, which builds
in an assumption about how the tarball was created.
To fix, test to see if the top-level run-script is present in the
current dir before trying to "cd kselftest"
Signed-off-by: Kevin Hilman <khilman@baylibre.com>
> kselftest: check for run script

- automated/linux/armnn/armnn-unit-tests.sh
- automated/linux/armnn/armnn-unit-tests.yaml
automated: linux: add the armnn unit tests
Adding armnn-unit-tests files to automated/linux/armnn/ in order to facilitate deployment to 64bit and 32bit devices in the LAVA lab as part of the armnn ci loop. This will deploy Deploy ArmNN as well as it's build UnitTests to a board which does not already contain them. If a board already has ArmNN installed it will also allow for the UnitTests to be automated and run. 
Signed-off-by: Theodore Grey <theodore.grey@linaro.org>
> armnn-unit-tests: creating test definitions for armnn unit tests

- automated/android/boottime/boottime.sh
- automated/android/boottime/boottime.yaml
- automated/android/boottime/device-script-master.sh
collect ro.boottime properties and replace dc with awk tool
and changed to get information from logcat dmesg buffer
instead of dmesg log which might not have all logs
Tested with following jobs:
db845c: https://lkft.validation.linaro.org/scheduler/job/1598559
hikey960: https://validation.linaro.org/scheduler/job/2073798
x15: https://lkft.validation.linaro.org/scheduler/job/1596656
Problems:
1. launcher displayed log not printed for the second boot
2. it's not stable to reboot on lava, often failed to get
the result for the second boot because of reboot problem.
need to check from both lava and device side
> boottime:  add support aosp master version

- automated/linux/igt/igt-test.yaml
The Chamelium IP address comes from device dict. It has to be ready
before we do the further tests.
> igt: Check Chamelium IP address before we go further

- automated/linux/cyclictest/cyclictest.sh
cyclictest output is meant for interactive terminals.  On dumb
terminals, it creates lots of noise resulting in massive logs.
Use quiet output (-q) to silence and just print a summary at the end
of the test.
Signed-off-by: Kevin Hilman <khilman@baylibre.com>
> cyclictest: use quiet output

- automated/lib/sh-test-lib
- automated/linux/cyclicdeadline/cyclicdeadline.sh
- automated/linux/cyclicdeadline/cyclicdeadline.yaml
- automated/linux/cyclictest/cyclictest.sh
- automated/linux/cyclictest/cyclictest.yaml
- automated/linux/pi-stress/pi-stress.sh
- automated/linux/pi-stress/pi-stress.yaml
- automated/linux/pmqtest/pmqtest.sh
- automated/linux/pmqtest/pmqtest.yaml
- automated/linux/ptsematest/ptsematest.sh
- automated/linux/ptsematest/ptsematest.yaml
- automated/linux/rt-migrate-test/rt-migrate-test.sh
- automated/linux/rt-migrate-test/rt-migrate-test.yaml
- automated/linux/signaltest/signaltest.sh
- automated/linux/signaltest/signaltest.yaml
- automated/linux/sigwaittest/sigwaittest.sh
- automated/linux/sigwaittest/sigwaittest.yaml
- automated/linux/svsematest/svsematest.sh
- automated/linux/svsematest/svsematest.yaml
This PR contains updates to the rt-tests testsuite. I am running this version for a while locally and feel comfortable to share it with upstream. See also https://github.com/kernelci/kernelci-core/issues/474
Changes:
- Add background command feature to all rt-tests. It utilizes a very simple form of background job control. I tried  to keep it a simple as possible and not trying to over engineer it at this point. It works reliable so far and I  think it's a good starting point.
- Silence the very verbose output of pi-stress and signaltest. All other rt-tests don't have a quiet option yet.  I'm planing to update and streamline all rt-tests in upstream soon. It's very annoying the small difference in each program.
~~- Remove the MAX_LATENCY argument again. It was not a good idea to mix …
> Preempt rt

- automated/linux/glmark2/glmark2.yaml
Newer versions of glmark2 has binaries like glmark2-es2
and glmark2-es2-drm.
> automated/linux: glmark2 allow to specify binary

- automated/linux/igt/igt-test.yaml
Fix the test result will be misleading when the network is unavailable.
1. Stop testing if the network is not available
2. Power cycle Chamelium before running igt Chamelium test
> igt: Check target network status before go further

- automated/lib/parse_rt_tests_results.py
- automated/linux/cyclicdeadline/cyclicdeadline.sh
- automated/linux/cyclicdeadline/cyclicdeadline.yaml
- automated/linux/cyclictest/cyclictest.sh
- automated/linux/cyclictest/cyclictest.yaml
- automated/linux/pmqtest/pmqtest.sh
- automated/linux/pmqtest/pmqtest.yaml
- automated/linux/ptsematest/ptsematest.sh
- automated/linux/ptsematest/ptsematest.yaml
- automated/linux/signaltest/signaltest.sh
- automated/linux/signaltest/signaltest.yaml
- automated/linux/sigwaittest/sigwaittest.sh
- automated/linux/sigwaittest/sigwaittest.yaml
- automated/linux/svsematest/svsematest.sh
- automated/linux/svsematest/svsematest.yaml
Remove the MAX_LATENCY argument again. It was not a good idea to mix execution/controlling of the test jobs and the performance measurement. This is done better in post processing. Rip it out again. I kept the parse_rt_tests_results.py for all rt-tests. The output format every test is slightly different and I was not able to get it working in a pure shell version. Until we have a better output format from upstream (yep planing to add this), let's stick with the current script.
> rt-tests: Remove MAX_LATENCY argument

- automated/linux/igt/control_chamelium.sh
- automated/linux/igt/igt-test.yaml
NetSNMP is required for igt Chamelium test to power cycle the Chamelium.
If it is not included in the test image, the test will be failed without
any clear hint. This patch will raise the error "CAN-NOT-reboot-Chamelium"
and abort the test if the Chamelium can not be reoot.
> igt: Abort the test if the Chamelium can not be reboot

- automated/linux/kselftest/skipfile-lkft.yaml
> selftests: pidfd: pidfd_wait hangs on linux next on all devices

- automated/linux/bootrr/bootrr.yaml
Currently bootrr tests are not executed as we are not moving into the
cloned repository. Fix it!
Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>
> linux: bootrr: Move into cloned repo before executing test

- plans/testplan2html.py
When we run the same test multiple times in a plan, it might be
convenient to use different names.
Signed-off-by: Nicolas Dechesne <nicolas.dechesne@linaro.org>
> testplan2html: allow testplan to override the test name

- automated/linux/kselftest/skipfile-lkft.yaml
ptrace vmaccess hangs on all devices on stable rc 4.19 branch and
lower kernel versions
ref:
https://bugs.linaro.org/show_bug.cgi?id=5683
> kselftest: skip hang test case ptrace vmaccess

- automated/linux/crypto/crypto.sh
In vanilla kernel, the tcrypt module is not built.
So in case of absent module, the test should be set as "skip" and not
"pass".
While fixing this, I just saw some return are missing in result().
> crypto: tcrypt module could be absent

- automated/linux/wlan-download/wlan-download-test.sh
Currently the test case extracts hostname from FILE_URL and tries to ping it.
But due to the server configuration, "testdata.validation.linaro.org" is not
accepting ping requests now. So, let's use google.com statically to ping. This
will rule out possible ping issues in future also.
Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>
> linux: wlan-download: Always ping google.com

- automated/utils/test-runner.py
In one of our tests, we had:
openssl-speed,openssl-version,pass,1.1.1g,version,SKIP_INSTALL=False
And when submitting to Squad, it failed because the measurement was
not a 'number' (e.g. 1.1.1g). With this patch, we make sure that all
measurements reported to Squad are integers or float.
Signed-off-by: Nicolas Dechesne <nicolas.dechesne@linaro.org>
> test-runner: make sure the measurement is a number

- automated/linux/kunit/kunit.sh
- automated/linux/kunit/kunit.yaml
KUnit is a lightweight unit testing and mocking framework for the Linux kernel.
KUnit consists of a kernel component, which provides a set of macros for easily
writing unit tests. Tests written against KUnit will run on kernel boot if
built-in, or when loaded if built as a module.
> kunit: Adding kunit tests

- automated/utils/test-runner.py
A manual test in the test plan runs a single test case, and we expect
a single result/metric. However test definitions in general are
typically made as series of test cases from a test suite.
It might be useful to run several test cases from a single manual test
suite. This patch adds a test_case_id attribute for manual test cases.
The test_case_id attrivute is set to the test suite name by
default. However when using the same test definition multiple times in
a test plan, we can override the test_case_id attribute from the test
plan, using a custom 'name'.
Here is an example of such a test plan:
manual:
- path: manual/generic/96boards-ls-gpio.yaml
repository: https://git.linaro.org/qa/test-definitions.git
name: gpio-A
- path: manual/generic/96boards-ls-gpio.yaml
repository: …
> test-runner: add support for test-case-id for manual tests

- automated/android/boottime/boottime.sh
- automated/android/boottime/boottime.yaml
- automated/android/noninteractive-tradefed/tradefed.sh
- automated/android/noninteractive-tradefed/tradefed.yaml
to workaround the naming conflict with the docker method.
with the docker method, ANDROID_SERIAL defined in the yaml file
or in the boottime.sh will cause the adb get-serialno failed to
get the device serial number.
If there is a need to specify the serial number for the script here,
plese export ANDROID_SERIAL explicitly before running the scripts.
> boottime.yaml: remove the passing of ANDROID_SERIAL

- automated/linux/ltp/skipfile-lkft.yaml
all other LTP test runs for 15 minutes at max but this test case
is running for 30 minutes which is too long. So skipping till it
get fixed upstream.
ref:
https://bugs.linaro.org/show_bug.cgi?id=5721
> LTP: Skip long running test cases bind06 cve-2018-18559

- automated/linux/ltp/skipfile-lkft.yaml
LTP tracing test case ftrace_stress_test.sh crashing on all devices.
ftrace_buffer_size_kb.sh: line 33: echo: write error: Cannot allocate memory
rcu: INFO: rcu_sched detected stalls on CPUs/tasks
RIP: 0010:queued_spin_lock_slowpath+0x46/0x1b0
ref:
https://bugs.linaro.org/show_bug.cgi?id=5722
> LTP: Adding ftrace_stress_test.sh as known issues

- sanity-check.sh
The repository is in a state where all files pass sanity check. This
means that the only interesting fact is when something breaks. This
change allows to only display failed test results instead of all.
> sanity-check: disable verbose output

- automated/linux/kselftest/skipfile-lkft.yaml
> selftests: skip kvm kvm_create_max_vcpus on arm64

- automated/linux/device-tree/device-tree.sh
- automated/linux/device-tree/device-tree.yaml
Prepare for adding a skip list. Make the test easier to read and follow.
* there's a couple of functions that aren't necessary.
* being root isn't necessary.
* added SPDX license identifier.
Signed-off-by: Fathi Boudra <fathi.boudra@linaro.org>
> automated: linux: device-tree: refactor the test

- automated/android/noninteractive-tradefed/monitor_fastboot.sh
- automated/android/noninteractive-tradefed/tradefed.yaml
Including the two change for where the boot image is saved inside the docker and workaround for the dmesg permission problem
> noninteractive-tradefed: add support for docker method

- automated/linux/pi-stress/pi-stress.sh
"-q" option will suppress "Current Inversions" to be displayed or redirected to a log file. 
Hence the pi-stress test is getting failed due to the condition statement where "Current Inversions" is being grep from log file.
**with "-q" option:**
----------------------------------------------------
$ pi_stress -q --duration 5s
Total inversion performed: 103858
Test Duration: 0 days, 0 hours, 0 minutes, 6 seconds
**without "-q" option:**
----------------------------------------------------
$ pi_stress --duration 5s
Starting PI Stress Test
Number of thread groups: 1
Duration of test run: 5 seconds
Number of inversions per group: unlimited
Admin thread SCHED_FIFO priority 4
1 groups of 3 threads will be created
High thread SCHED_FIFO priority 3
Med thread SCHED_FIFO priority 2
Low thread …
> Remove "-q" option from pi_stress

- plans/testplan2html.py
We introduced a regression in
e6f1632c8a03 (plans: support custom templates for rendering testplans)
Up until this commit the default testplan_template was testplan.html
for v1 and testplan_v2.html for v2. However this commit broke this
assumption, and we ended up with testplan.html for both v1 and
v2. This patch restores the expected default names.
Signed-off-by: Nicolas Dechesne <nicolas.dechesne@linaro.org>
> testplan2html: fix default template name

- automated/utils/test-runner.py
test-definitions/automated/bin/test-runner:325:
SyntaxWarning: "is" with a literal. Did you mean "=="?
> automated: utils: test-runner: fix syntax warning

- automated/android/workload-automation3/aep-energy-config.sh
- automated/android/workload-automation3/aep-install.sh
The send-to-lava.sh script expects a single word as a test case name
followed by the result. If the test case name contains multiple words
the script assumes that the second word is the test result. Let's fix
the test cases to be in the expected format to prevent errors like
this:
> echo  AEP config installed pass
> ...
> ../../utils/send-to-lava.sh ./output/result.txt
> <LAVA_SIGNAL_TESTCASE TEST_CASE_ID=AEP RESULT=config>
> Received signal: <TESTCASE> TEST_CASE_ID=AEP RESULT=config
> Bad test result: config
Signed-off-by: Georgi Djakov <georgi.djakov@linaro.org>
> workload-automation3: Fix test_case names

- automated/linux/perf/perf.sh
perf test results parser updated to remove some special characters in
test case names for easy results parsing by LAVA.
ref:
perf test: Output sub testing result in cs-etm
https://lore.kernel.org/lkml/20210215115944.535986-1-leo.yan@linaro.org/
> linux: perf: perf test results parser update

- .github/workflows/test-plans-pipeline.yml
- automated/android/multinode/tradefed/utils.py
- automated/android/tradefed/result_parser.py
- automated/lib/android_ui_wifi.py
- automated/utils/test-runner.py
Black should run with --check, so it exits with exit code 1, not 0 plus
doesn't reformat, but fails the build.
Signed-off-by: Benjamin Copeland <ben.copeland@linaro.org>
> CI: Run black with --check

- README.md
Updating our README to use GitHub workflow status, instead of TravisCI
as this is no longer used.
Signed-off-by: Benjamin Copeland <ben.copeland@linaro.org>
> README: Use GitHub actions workflow status badge

- automated/linux/packetdrill/packetdrill.sh
- automated/linux/packetdrill/packetdrill.yaml
Adding packetdrill test suite to Linaro test definitions.
The packetdrill scripting tool enables quick, precise tests for entire
TCP/UDP/IPv4/IPv6 network stacks, from the system call layer down to
the NIC hardware. packetdrill currently works on Linux, FreeBSD,
OpenBSD, and NetBSD. It can test network stack behavior over physical
NICs on a LAN, or on a single machine using a tun virtual network
device.
> linux: Adding packetdrill test suite

- automated/linux/tvm/tvm-unit-tests.sh
- automated/linux/tvm/tvm-unit-tests.yaml
Initial commit for the tvm-ci-build. Creation of automated/linux/tvm:
tvm-unit-tests.sh and tvm-unit-tests.yaml for deployment of tvm tests to
devices.
Signed-off-by: Theodore Grey <theodore.grey@linaro.org>
> automated: linux: add tvm tests

- automated/linux/crypto/cryptsetup.sh
- automated/linux/crypto/cryptsetup.yaml
Use the cryptsetup utility to run some basic benchmarks.
HASH and CIPHER params are used to indicate which algorithms to
benchmark.
For CIPHER, we concatenate the alg name with the key size, so that we
can test multiple sizes.
Here is a more complex value for CIPERH, which can be used in a test
plan:
CIPHER='aes-cbc_128 aes-cbc_256 aes-xts_256 aes-xts_512 \
serpent-cbc_128 serpent-cbc_256 serpent-xts_256 serpent-xts_512 \
twofish-cbc_128 twofish-cbc_256 twofish-xts_256 twofish-xts_512'
Here is a sample output, running on an x86 laptop:
<TEST_CASE_ID=cryptsetup-version RESULT=pass>
<TEST_CASE_ID=cryptsetup-benchmark-hash-sha1 RESULT=pass>
<TEST_CASE_ID=cryptsetup-benchmark-sha1 RESULT=pass MEASUREMENT=1646116 UNITS=iter/s>
<TEST_CASE_ID=cryptsetup-benchmark-hash-sha256 RESULT=pass> …
> crypto: add cryptsetup benchmark test

- automated/linux/fwts/fwts.sh
- automated/linux/fwts/fwts.yaml
Add a skip test variable if a few tests needs to be skipped.
Instead of having to list all 80 tests in the TESTS variable just list
the few tests you want to skip in variable SKIP_TESTS.
> automated: linux: fwts: add a variable to skip tests

- automated/linux/aep-pre-post/lisa.sh
Convert the LISA environment to python3, as python2 is no longer
supported and it would be nice to align this also with other tools
and libraries that have already moved to python3.
Signed-off-by: Georgi Djakov <georgi.djakov@linaro.org>
> linux/aep-pre-post: Switch to python3 environment for LISA

- automated/linux/workload-automation3/workload-automation.sh
Save the IPv4 address of the target to /etc/hosts to make it easier
for scripts to connect to the target by using just a fixed hostname.
Signed-off-by: Georgi Djakov <georgi.djakov@linaro.org>
> workload-automation3: Save the lava-target-ip to hosts

- automated/linux/packetdrill/packetdrill.sh
- automated/linux/packetdrill/packetdrill.yaml
When packetdrill is pre-installed on the rootfs we do not have
to install pre-required packages and build the packetdrill.
so move this section when SKIP_INSTALL is not true.
> packetdrill: Fix skip install section

- automated/utils/test-runner.py
With black-21.4b1-py3-none-any.whl the following black formatting issue shows up
with a diff like this:
-    """ Run a shell command. If target is specified, ssh to the given target first. """
+    """Run a shell command. If target is specified, ssh to the given target first."""
> automated: utils: test-runner: fix black formatting issues

- automated/android/noninteractive-tradefed/monitor_fastboot.sh
but with the vendor_boot.img excluded
> monitor_fastboot.sh: support for the file name of boot.img

- automated/linux/kselftest/skipfile-lkft.yaml
The kselftest test case ftracetest hangs on all devices
for all branches. lets skip this test case from runs.
> kselftest: skip ftracetest on all branches

- automated/linux/mmtests/json-to-lava.py
- automated/linux/mmtests/mmtests.sh
- automated/linux/mmtests/mmtests.yaml
MMTests is a configurable test suite that runs performance tests
against arbitrary workloads.
This commit adds to the test set the mmtests suite and exports
the test results in a JSON file.
Signed-off-by: Mirco Romagnoli <romagnoli.mirco@gmail.com>
> automated: linux: add mmtests benchmarks

- automated/utils/upload-to-artifactorial.sh
Busybox find command with argument '-regex' doesn't work, use 'grep -E'
instead for pattern filtering.
> Fix artifacts publishing with busybox

- automated/linux/mmtests/mmtests.yaml
> mmtests: mmtests.yaml: add mandatory keywords maintainer, os and devices

- automated/linux/kernel-config-checker/kernel-config-checker.sh
Results reported with check_return should not include white spaces and
semi-colons.
> automated: linux: fix kernel-config-checker results

- automated/linux/network-basic/network-basic.sh
- automated/linux/network-basic/network-basic.yaml
Allow using udhcpc (or some other) DHCP client. Also allow to use wget
instead of curl for file download. This is useful on systems where there
are only pre-installed utilities and no way to install new software.
> linux: customize network-basic test

- automated/linux/docker-networking/docker-networking.sh
Add IPv4 ping test from container to 'localhost'. Container runs in host
networking mode.
> automated: linux: add ping test from container

- automated/linux/rt-migrate-test/rt-migrate-test.sh
The variable 'r' contains " pass" value with an extra whitespace added.
To keep the results in an organized manner, extra whitespace should be avoided
in between columns of result.txt file.
Signed-off-by: Vidyasagar G C <vidyasagar_gc@mentor.com>
> Remove extra whitespace in the value of variable 'r'

- automated/lib/sh-test-lib
cleanup return and exit, also fix the if statement checking if not equal
to 'debugfs'.
> lib: sh-test-lib: fixup function mount_debugfs

- automated/linux/ltp/skipfile-lkft.yaml
LTP smoketest ping01 not supported on juno-r2 running on 4.4 branch.
module veth: overflow in relocation type 261 val ffffffbffc000000
RTNETLINK answers: Operation not supported
ping01 1 TBROK: ip link add name ltp_ns_veth1 type veth peer name ltp_ns_veth2 failed
> LTP: Skip ping01 on juno-r2 for 4.4 branch

- automated/android/noninteractive-tradefed/setup.sh
to work with aosp-android11, aosp-android12 too
> noninteractive-tradefed: support more ANDROID_VERSION

- automated/utils/test-runner.py
test-runner will call "rm -rf" on the directory it created temporarily
on the remote target. This should remove all residual files created in
the process of running a test.
> automated: cleanup target after remote testing

- automated/linux/ima/ima.sh
When IMA test is executed a long time after the boot, the initialization
message might already be gone from dmesg buffer. In this case the test
will falsly report 'fail' result. This patch fixes the issue by checking
if the actual policy file exists on the sysfs.
> automated: fix IMA test to avoid using dmesg

- automated/linux/mmtests/json-to-lava.py
- automated/linux/mmtests/mmtests.sh
- automated/linux/mmtests/mmtests.yaml
mmtests/json-to-lava: add support for altreports and multiple json files
Change the structure of the LAVA data to push to squad as following:
<module_name>;<op>;<iteration>;<sample> pass <value>
The test name field in the second position had been dropped, since the
name of the origin folder is always something generic like "benchmark",
therefore useless
The <op> field now has a double function. If not prefixed with an "_",
it represent the operation which generated the relative data, as it was before.
If the content starts with "_", it now represent additional data to add
at the top level of the corresponding json file.
E.g, the line:
dbench4tput;_Cmd;0;b'ZGJlbmNoIC1EIC9ob2 ... lLXRpbWUgMQo=' pass 0
represent the _Cmd field in the json, which data in the <sample> spot
can be decoded from …
> mmtests: export multiple json files into lava format

- automated/android/noninteractive-tradefed/setup.sh
- automated/android/noninteractive-tradefed/tradefed.yaml
to avoid the shutdown of device caused high temperature
when run the cts vts jobs
> noninteractive-tradefed: support to run under powersave governor policy

- automated/linux/timesyncd/timesyncd.yaml
- automated/linux/timesyncd/timesynctest.py
- automated/linux/timesyncd/timesynctest.sh
This test checks whether timesyncd is running and synchronizing to NTP
server. As additional check reference NTP server's time is compared with
local system time.
> automated: linux: add timesyncd NTP sync test

- automated/linux/ltp/ltp.sh
The package 'au' was probably added by mistake since.
'No match for argument: au'
Remove the faulty package 'au' from fedora.
Fixes: 67acee6c1a53 ("automated: linux: ltp: incorporate building LTP from git")
> ltp: fix fedora package dependency 'au'

- automated/linux/mmtests/json-to-lava.py
- automated/linux/mmtests/mmtests.sh
- sanity-check.sh
Since the env variables used in mmtests to perform each specific
test change based on the evironment and the test itself, we
want to save those config in SQUAD as well, to be retrieved
later by the reporting tool.
In order to do so, an associative array is needed to retrieve the
correct env variables for each test, since the name of said variables
does not always start with the name of the tests.
The syntax follows the one used previosly for the other
additional parameters:
dbench4_#CONFIG-DBENCH-DURATION-BASE_0_30 pass 0
dbench4_#CONFIG-DBENCH-FSYNC_0_no pass 0
dbench4_#CONFIG-DBENCH-MAX-CLIENTS_0_1 pass 0
json-to-lava.py: split the command string in pieces of 25
characters, in order to avoid LAVA breaking with strings too long
Signed-off-by: Federico Gelmetti <federico.gelmo@gmail.com>
> mmtests: add config settings in the exported LAVA output

- automated/linux/kunit/kunit.sh
When doing modprobe on the modules the file suffix shouldn't be part
there. Removing the '.ko' so we do 'modprobe name' only.
> kunit: fix modprobe names

- automated/linux/network-manager/network-manager.sh
NetworkManager caches connectivity status. Sometimes this causes an
unexpected failure in the test. This patch forces NM to check for the
connectivity status every time there is a change in the interfaces.
> automated: linux: force connectivity check in NM test

- automated/linux/mmtests/mmtests.sh
NUMCPUS setting variable was not correctly retrieved when saving
the test config settings into the exported json.
Fix this value to avoid a misalignment between the test data and
the command string reported.
Signed-off-by: Federico Gelmetti <federico.gelmo@gmail.com>
> mmtests: fix retrieval of NUMCPUS config variable

- automated/linux/docker/docker.sh
When running basic docker test, the container is left in the stopped
state after the execution completes. This patch forces docker to
remove the container.
> automated: linux: remove docker container after the test

- automated/linux/vdsotest/vdsotest.sh
- automated/linux/vdsotest/vdsotest.yaml
Adding new vdsotest definitions for LKFT test plan.
The "vDSO" (virtual dynamic shared object) is a small shared
library that the kernel automatically maps into the address space
of all user-space applications.
ref:
Implement vdsotest test-definitions in LKFT test plan
https://linaro.atlassian.net/browse/LKQ-686
> linux: Adding vdsotest

- automated/linux/mmtests/json-to-lava.py
- automated/linux/mmtests/mmtests.sh
mmtests.sh: adapt for correct generation of json files
when the workload supplied is composed by more than one benchmark,
as in the case of workload-aim9-pagealloc
json-to-lava: fix incorrect LAVA output when supplied with
operation names containing "/"
Signed-off-by: Federico Gelmetti <federico.gelmo@gmail.com>
> mmtests: adapt for workloads with multiple subtests

- automated/linux/disable-aklite-reboot/disable-aklite-reboot.sh
Sometimes there is a race between systemd aktualizr-lite starting and
calling it from the test script. This might cause non-zero exit from the
sript and result in not registering the test result. This patch should
prevent this from happening.
> automated: linux: force clean exit from aklite test

- automated/linux/kselftest/skipfile-lkft.yaml
kselftest net tls test case hangs on all devices so adding tls test case to
skiplist.
> kselftest: Adding net tls to skiplist due to hang

- automated/linux/ota-rollback/download-update.sh
- automated/linux/ota-rollback/sh-lib
- automated/linux/ota-rollback/verify-reboot.sh
- automated/linux/ota-rollback/verify-rollback.sh
OTA rollback test had issues with devices that use RPMB instead of u-boot environment.  Some variables are only set by aktualizr-lite when is starts. This patch fixes the problem.
> OTA rollback debug

- automated/linux/spectre-meltdown-checker-test/bin/spectre-meltdown-checker.sh
- automated/linux/spectre-meltdown-checker-test/spectre-meltdown-checker-test.sh
- automated/linux/spectre-meltdown-checker-test/spectre-meltdown-checker-test.yaml
Release notes for v0.45:
https://github.com/speed47/spectre-meltdown-checker/releases/tag/v0.45
Signed-off-by: Alice Ferrazzi <alice.ferrazzi@miraclelinux.com>
> spectre-meltdown-checker: Update to 0.45

- automated/lib/sh-test-lib
Update the combinations that linux can report back via 'uname -m'.
This makes use able to run:
- "armv{4,4t,5t,5te,5tej,6,7,7m}l" for little-endian arm32 kernels
- "armv{4,4t,5t,5te,5tej}b for big-endian arm32 (be32) kernels
- "armv{6,7,7m}b" for big-endian arm32 (be8) kernels
- "armv8l" for little-endian arm64 kernels in 32-bit mode
- "armv8b" for big-endian arm64 kernels in 32-bit mode
- "aarch64" for little-endian arm64 kernels in 64-bit mode
- "aarch64_be" for big-endian arm64 kernels in 64-bit mode
For now the bigendian flavors are there but commented out for completeness.
> lib: sh-test-lib: update detect_abi combinations

- automated/linux/ota-rollback/download-update.sh
When aktualizr-lite starts it takes a few seconds before it sets proper
u-boot variables. Before this patch the variables were read before
aklite had chance to set their values.
> automated: linux: fix ota-rollback timing issue

- automated/linux/spectre-meltdown-checker-test/spectre-meltdown-checker-test.sh
Since spectre-meltdown-checker.sh does not have execute permission,
so an error will occur when executing.
```
+ cd ./automated/linux/spectre-meltdown-checker-test
+ ./spectre-meltdown-checker-test.sh -s False -v v0.45 -w False
./spectre-meltdown-checker-test.sh: 46:
./spectre-meltdown-checker-test.sh: ./spectre-meltdown-checker.sh:
Permission denied
+ ../../utils/send-to-lava.sh ./output/result.txt
```
There are several ways to work around this issue, but I can do so by
running it with /bin/sh at run time.
Signed-off-by: Nobuhiro Iwamatsu <nobuhiro1.iwamatsu@toshiba.co.jp>
> spectre-meltdown-checker: Add execution by /bin/sh

- automated/lib/parse_rt_tests_results.py
- automated/linux/rtla/parse_rtla.py
- automated/linux/rtla/rtla-osnoise.sh
- automated/linux/rtla/rtla-osnoise.yaml
- automated/linux/rtla/rtla-timerlat.sh
- automated/linux/rtla/rtla-timerlat.yaml
The rtla is a meta-tool that includes a set of commands that aims to analyze the real-time properties of Linux. But instead of testing Linux as a black box, rtla leverages kernel tracing capabilities to provide precise information about the properties and root causes of unexpected results.
- osnoise
Gives information about the operating system noise (osnoise).
- timerlat
Measures the IRQ and thread timer latency.
See for more information: https://docs.kernel.org/tools/rtla/rtla.html
This is an initial integration into test-definitions, following the rt-tests as mach as possible (even faking the JSON format output). Maybe upstream will add support for native JSON output but until let's role with this format.
I haven't added any access to any command line options except the duration …
> Add Real-time Linux Analysis tool

- automated/linux/tensorflow/imagenet-resnet50.sh
- automated/linux/tensorflow/imagenet-resnet50.yaml
- automated/linux/tensorflow/imagenet-ssd-resnet34.sh
- automated/linux/tensorflow/imagenet-ssd-resnet34.yaml
- automated/linux/tensorflow/ssd-mobilenet.sh
- automated/linux/tensorflow/ssd-mobilenet.yaml
- automated/linux/tensorflow/tensorflow-utils.sh
Creating automation of Tensorflow MLPerf tests on the D05 : resnet50, ssd-resnet32, and ssd-mobilenet. These scripts can be run with or without mounting the device to a NFS drive with pre downloaded data sets (only available for devices in Cambridge COLO).
These scripts run a Tensorflow Benchmark with the equivalent dataset (resnet50, ssd-mobilenet etc.) and are meant to give accurate benchmark data on the Tensorflow Library.
Signed-off-by: Theodore Grey <theodore.grey@linaro.org>
> Tensorflow MLPerf tests for D05

- automated/linux/ota-rollback/README.md
README describes how to use the test .yaml files and gives an example
test section of LAVA test job.
> automated: linux: add README to ota-rollback

- automated/linux/ltp/skipfile-lkft.yaml
Tuxrun is a commandline tool for testing Linux on QEMU or FVP.
> linux: ltp: update skipfile-lkft with tuxrun targets

- automated/linux/libcurl/Dockerfile
- automated/linux/libcurl/README.md
- automated/linux/libcurl/httpd.conf
- automated/linux/libcurl/libcurl.sh
- automated/linux/libcurl/libcurl.yaml
This test covers the bug in libcurl that results in Out of memory
exception when dealing with HTTPS server with self-signed certificate.
When certificate lacks SAN fieds, libcurl would quit. Github error:
https://github.com/curl/curl/issues/8559
The bug was fixed in libcurl:
https://github.com/curl/curl/pull/8560
The fix is not propagated to all distros yet (as of July 2022).
> automated: linux: add libcurl SAN-less test

- automated/linux/ota-rollback/download-update.sh
- automated/linux/ota-rollback/verify-reboot.sh
- automated/linux/ota-rollback/verify-rollback.sh
- automated/linux/ota-update/download-update.sh
- automated/linux/ota-update/verify-reboot.sh
- automated/linux/ota-update/verify-update.sh
When performing OTA update/rollback on open board variables are kept in
u-boot env. When the same is performed on a closed board, variables are
kept in RPMB. Due to historical reasons the "fiovb" prefix is not
present in RPMB variables. This patch aligns the current behaviour of
the test with the software.
> automated: linux: ota update/rollback variable fix

- automated/linux/lmp-device-register/lmp-device-register.sh
- automated/linux/lmp-device-register/lmp-device-register.yaml
- automated/linux/lmp-device-register/z-99-aklite-callback.toml
The test exercises basic features of FoundriesFactory
lmp-device-register utility.
> automated: linux: add lmp-device-register test

- automated/linux/ltp/skipfile-lkft.yaml
The identified long running and hang test cases should be skipped on
all device types.
> ltp: skip hang tests on all devices

- automated/lib/android-test-lib
when ANDROID_SERIAL is empty, to work around the following problem
++ adb get-serialno
error: device '' not found
+ ANDROID_SERIAL=
> initialize_adb: unset ANDROID_SERIAL before get-serialno

- automated/linux/ota-rollback/download-update.sh
- automated/linux/ota-rollback/download-update.yaml
- automated/linux/ota-rollback/z-99-aklite-callback-ostree.toml
This option will exercise a different code path in aktualizr-lite and
cover potential bug that would push the system towards rollback cycle.
> automated: linux: Add 'ostree' option to ota-rollback

- docs/test-writing-guidelines.md
Wiki syntax requires space after heading hash.
See rendered output on
https://github.com/Linaro/test-definitions/blob/master/docs/test-writing-guidelines.md
Signed-off-by: Mikko Rapeli <mikko.rapeli@linaro.org>
> test-writing-guidelines.md: fix headings

- automated/linux/ltp/ltp.sh
- automated/linux/ltp/ltp.yaml
This will improve the test time if running LTP 'syscalls' that contains almost 1400 individual tests.
With 'SHARD_NUMBER' set to 10, that will split up the syscalls in 10 buckets, and if 10 jobs gets created and run on 10 different devices with different 'SHARD_INDEX' set from 1, 2, ..., 9, 10 that will speed up the overall run of syscalls.
> automated: ltp: support sharding of LTP's subsuites

- automated/android/noninteractive-tradefed/tradefed.sh
This reverts commit 1e5f85192b08fd3a9c4ff91e522ff4e00dffdac6. Reason: according to what Kelley said:
yes, we just need to clear the current cache entry for the old S3 url
after that, the caching settings should prevent those from being saved
so I think one successful run with --no-cache, and subsequent runs are good to go
> Revert "tradefed.sh: pass --no-cache to wget"

- automated/linux/kselftest/kselftest.sh
- automated/linux/kselftest/kselftest.yaml
This will improve the test time if running kselftest's subsuites.
With 'SHARD_NUMBER' set to 10, that will split up the subsuite in 10
buckets, and if 10 jobs gets created and run on 10 different devices
with different 'SHARD_INDEX' set from 1, 2, ..., 9, 10 that will
speed up the overall run of that subsuite.
> kselftest: support sharding of kselftest's subsuites

- automated/lib/parse_rt_tests_results.py
parse_rt_tests_results.py has not migrated to python3. This update the shebang to python3.
Signed-off-by: Nobuhiro Iwamatsu <nobuhiro1.iwamatsu@toshiba.co.jp>
> automated: libs: parse_rt_tests_results.py: Update shebang from python to python3

- automated/linux/ota-rollback/download-update.sh
- automated/linux/ota-rollback/download-update.yaml
On some machines u-boot image/binary has different name than default. This patch allows to set the file name to be corrupted during the test.
> automated: linux: ota-rollback allow different u-boot name

- automated/linux/kselftest/kselftest.sh
When searching for 'sub-tests' in kselftest-list.txt don't write back to the same file, use a kselftest-list.tmp file.
> automated: linux: kselftest: don't overwrite file

- automated/linux/ota-rollback/download-update.sh
When doing OTA upgrade ostree might decide that kernel image didn't change and keep just single file for "old" and "new" sysroot versions. This means that corrupting the kernel will brick the board and the rollback wouldn't be possible. This patch addresses the issue by creating a "fake" kernel and updating uEnv.txt. This is a bit more invasive than the previous approach but seems to be the simplest way of forcing "bad kernel" based rollback.
> automated: linux: allow ostree to keep single kernel

- automated/linux/kunit/kunit.sh
- automated/linux/kunit/parse-output.py
Slugify test names so LAVA can understand the format. This will work with the old kunit way
ok 1 - test_1..
and
ok 1 test_1..
> automated: linux: kunit: fix parsing

- automated/linux/ptest/ptest.py
- automated/linux/ptest/ptest.yaml
This PR fixes:
- ptest-runner timeouts on slower machines, by allowing to specify timeout
- merging test names containing spaces in a single word
> automated: linux: ptest: Fix test names reporting and timeout

- automated/linux/ltp/ltp.sh
When running multiple tests in different test sections in the LAVA job definition file, the alltests file was only adding more and more tests to the file. Which lead to that the first tests that was added was running in all the following tests as well.
Ensuring to delete the 'alltests' file before generating the file, will fix the problem of running the same set of tests in the following test runs.
Reported-by: Naresh Kamboju <naresh.kamboju@linaro.org>
> ltp: sharding: remove the tmp file before creation

- automated/utils/send-to-lava.sh
Instead of launching a subshell with `echo` piped through `awk`, use shell expression expansion to retrieve the test name and the test result.
In simple cases where there are mostly PASS/FAIL/SKIP results, this is a speed-up improvement of +80%.
> send-to-lava: Speed up parsing of simple test results

- automated/linux/perf/parse-output.py
- automated/linux/perf/perf.sh
Rewrite the parser in python, to simplify and to fix a bug in the old parser.  The old parser added tests names like these. "Adding-21887790a5f1f038192425e4792a66110054c22a-/tmp/perf.ex.SHA1.q8H pass"
Simplify the parsing and fixing the '/tmp/perf..' random bug.
> automated: linux: perf: simplify and fix logparser

- automated/linux/perf/perf.sh
The script is expecting inputs on stdin.
> perf: fix argument parsing to parse-output.py

- automated/linux/kselftest/kselftest.sh
- automated/linux/kselftest/parse-output.py
Update to use the same parser that 'kunit' uses.
Since there are a lot of subtests in kselftest that produce the same output like 'clone3 438_result_22_matches_expectation_22' thats why the subtest number are included into the test name.
The subsuite tests in 'kunit' are uniq, thats why we don't need to include the subtest number.
> automated: kselftest: update parser

- automated/linux/secure-boot/secure-boot-enabled.yaml
This PR fixes the link to the UEFI specifications in the `secure-boot-enabled.yaml` file.
The [old link](https://shorturl.at/fpLV6) does not actually redirect to the PDF file of the UEFI specifications. Instead, it leads to a Google search page for "fitzroy falls walk".
Instead of linking to a PDF file, this PR links to the HTML version of the UEFI specifications to make it more easily navigable.
Signed-off-by: James R T <jamestiotio@gmail.com>
> secure-boot: Fix link to UEFI specs

- automated/linux/kselftest/kselftest.sh
pushd is a bash enhancement to the POSIX-specified Bourne Shell. Use 'cd' instead.
> automated: kselftest: remove pushd/popd in favor for cd

- automated/linux/kselftest/skipfile-lkft.yaml
The kselftest arm64 fp-stress test case hangs on qemu-arm64. Due to this hang test other tests not being run.
> kselftest: skipfile-lkft: Adding arm64 fp-stress to skipfile

- automated/linux/kselftest/parse-output.py
Forgot to set the fail output before removing the extra '_selftests_' from the output.
Fixes: 65be76866f2d ("automated: kselftest: update parser")
Reported-by: Naresh Kamboju <naresh.kamboju@linaro.org>
> automated: kselftest: parse-output: fix fail cases

- automated/linux/kselftest/kselftest.sh
- automated/linux/kselftest/parse-output.py
After upgrading perl parser to python few small issues was discovered. One of them is failure to parse "not ok" result, another one is likely https://github.com/Linaro/test-definitions/pull/418 require more proper fix in some conditions.
Both commits tested on staging in kernelci and collabora LAVA: https://lava.collabora.dev/scheduler/job/8642420
> Fix small parser issues

- automated/lib/sh-test-lib
Since skipgen has been observed to fail with no output log the error code from it in order to aid debugging.
> sh-test-lib: Log exit code from skipgen

- automated/linux/kselftest/parse-output.py
When parsing results from tests produced from tests in nested test programs such as:
parse-output.py generates test names like:
arm64_syscall-abi_1_getpid_FPSIMD pass
which include the test number. Since for programs using the kselftest framework the test number is allocated dynamically by the framework the test number is not really stable, meaning that including it in the test name can impede matching of results between test runs by systems. Instead discard this number and generate test names like:
arm64_syscall-abi_getpid_FPSIMD
which will be stable as other tests are added and removed like those for top level suites.
> automated: kselftest: Don't include test numbers for nested suites

- automated/linux/kvm-unit-tests/kvm-unit-tests.sh
Rather than requiring kvm-unit-tests be built for every test run support using a preinstalled copy.
> kvm-unit-tests: Support preinstallation of kvm-unit-tests

- mkdocs_plugin/testdefinitionsmkdocs/__init__.py
Black release 22.12.0 didn't complain. But now with black release 23.1.0, black enforce empty lines before classes and functions with sticky leading comments.
Link: https://black.readthedocs.io/en/stable/change_log.html#id1
> mkdocs_plugin: testdefinitionsmkdocs: fix black warning

- automated/linux/kselftest/skipfile-lkft.yaml
LKFT test farm noticed that fp-stress test is getting pass on
latest Qemu version 7.2.  Now fp-stress should be unskipped.
This reverts commit c61b8f17cf95547ae34d5bab1d9cd9375965885c.
> Revert "kselftest: skipfile-lkft: Adding arm64 fp-stress to skipfile"

- automated/linux/ota-update/verify-update.sh
- automated/linux/ota-update/verify-update.yaml
Some boards use boot ROM that doesn't allow to boot from secondary path. In such cases the OTA update will overwrite the primary u-boot. When this happens is_secondary u-boot variable is set to 0. This patch adds support for this use case to ota-update test.
> automated: fix OTA verification without secondary path

- automated/linux/kvm-unit-tests/kvm-unit-tests.sh
Currently the log message we print when we skip installing dependencies
looks very much like it's skipping the tests themselves.  Clarify what
is happening.
> kvm-unit-tests: Clarify logging for SKIP_INSTALL

- automated/linux/kvm-unit-tests/kvm-unit-tests.sh
The script is checking for run-tests.sh when looking to see if we have a
preinstalled copy of the tests but the script that the tests install is
run_tests.sh with an _ not a -.  Fix that.
> kvm-unit-tests: Fix naming of run_tests.sh

- automated/linux/kselftest/skipfile-lkft.yaml
The ftrace tests are currently skipped with references to some kernel
bugs from back in 2017.  Given that developers use these tests regularly
without seeing problems and the age of the bugs it seems likely that
they are no longer relevant, testing seems to indicate that's the case
for at least arm64.  Remove the skip.
> kselftest: Run the ftrace tests

- automated/utils/upload-to-artifactorial.sh
CURL_VERBOSE_FLAG="" by default. `curl "" ...` works but reports `bad/illegal format or missing URL` warning. Removing the double quotes on the variable fixes the issue.
> utils: fix bad/illegal format or missing URL warning from curl

- automated/android/noninteractive-tradefed/tradefed.sh
- automated/android/noninteractive-tradefed/tradefed.yaml
to report network failures early.
Tested with the following jobs:
https://validation.linaro.org/scheduler/job/3939143: network enabled on the DUT side after wifi setup
https://validation.linaro.org/scheduler/job/3939144: network not available on the DUT side
https://lkft.validation.linaro.org/scheduler/job/6300769: network available with the default ethernet cable
> noninteractive-tradefed: add ping test

- automated/linux/optee/optee-xtest.sh
- automated/linux/optee/optee-xtest.yaml
When running xtest on the device with secure element (SE050) some tests generate objects in the element. These objects are not deleted by the tests:
https://github.com/OP-TEE/optee_test/issues/652
In the long run secure element runs out of space and all tests start failing with strange errors. To mitigate this the script will call reset method on SE050 after all tests are completed. This should at least fix the problem of residual objects.
> automated: linux: add se05x reset after running xtest

- automated/android/noninteractive-tradefed/tradefed.sh
to make sure if the problem is with dns or something else
> noninteractive-tradefed: run ping 8.8.8.8 for network failures

- automated/android/noninteractive-tradefed/tradefed.sh
only lkft-cache.lkftlab is supported with this PR, it should be more generic when another kisscache server is supported.
> noninteractive-tradefed: support to use lkft-cache for cache

- automated/android/noninteractive-tradefed/tradefed.sh
so that the network failure could be reported
as lava job fatal error
> noninteractive-tradefed: do not exit for debug command

- automated/linux/optee/optee-xtest.yaml
Previously failed tests can leave some data in storage which fails the tests later on unless data is cleared. --clear-storage option is new to xtest:
https://github.com/OP-TEE/optee_test/pull/670
See also:
https://gitlab.com/Linaro/trustedsubstrate/meta-ledge-secure/-/merge_requests/60
Ignore return values since the option may not exist in all xtest versions and it can also report failures.
> optee-xtest.yml: clear storage before executing tests

- automated/linux/factory-reset/prepare-reset.sh
- automated/linux/factory-reset/prepare-reset.yaml
- automated/linux/factory-reset/z-99-aklite-callback.toml
When performing factory reset it is assumed the device is up to date with respect to aktualizr-lite and ostree. This patch allows to add a tag to the sota.toml which forces aktualizr-lite to use this tag. This gives a chance to add a tag to only one target on the backend side and avoid OTA update during the test.
> automated: linux: avoid OTA in factory-reset test

- automated/linux/kselftest/parse-output.py
Skip could only be matched on '# SKIP'. However, it can also be '# skip' or even '# skipped'.
Without this patch the tests was reported as "pass" and not as "skip".
Suggested-by: Matthieu Baerts <matthieu.baerts@tessares.net>
> kselftest: parse-output: fix matching 'skip'

- automated/linux/optee/optee-xtest.sh
When running xtest on a device with secure element (SE050) there are some objects left behind. This patch fixes the cleanup of the objects on LmP platform.
> automated: linux: fix cleanup after xtest

- automated/android/noninteractive-tradefed/setup.sh
since Android10 is deprecated, and OpenJDK11 could be used for all later versisons, here make it simple
to only use OpenJDK11 to avoid changes for different Android versions in the future
> noninteractive-tradefed: drop check for ANDROID_VERSION

- automated/linux/xenomai4/xenomai4-smoke.sh
- automated/linux/xenomai4/xenomai4.yaml
This patch adds a smoke test for xenomai4 RT solution for kernel. By default the test runs a list of tests predefined in 'evl' tool. The output is PASS/FAIL/SKIP for each test. Tests report SKIP when the required configs are not available in the kernel.
> automated: linux: add xenomai4 test suite

- automated/android/noninteractive-tradefed/setup.sh
Otherwise there will be version not support problem reported when run the cts tests
> noninteractive-tradefed: install OpenJDK17 for Android14

- automated/linux/factory-reset/prepare-reset.sh
Enable proper auto-registration with tags. Note: this patch requires support in the lmp-device-auto-register script.
> automated: linux: factory-reset: fix device registration

- automated/linux/kselftest/kselftest.sh
Adding new test case to check sharding status.
When sharding file is empty, test will fail and exit.
Suggested-by:  Anders Roxell <anders.roxell@linaro.org>
> kselftest: Adding new test case for sharding status

- automated/linux/rcutorture/rcutorture.sh
- automated/linux/rcutorture/rcutorture.yaml
No need to check for fragments since it can be built into the kernel and then run on boot.
> automated: linux: rcutorture: drop config checking

- automated/android/apk-automation/apk-automation.sh
as numpy 1.25.1 requires 3.9+ python.
Reading https://pypi.org/simple/numpy/
Downloading https://files.pythonhosted.org/packages/cf/7a/f68d1d658a0e68084097beb212fa9356fee7eabff8b57231cc4acb555b12/numpy-1.25.1.tar.gz#sha256=9a3a9f3a61480cc086117b426a8bd86869c213fc4072e606f01c4e4b66eb92bf
Best match: numpy 1.25.1
Processing numpy-1.25.1.tar.gz
Writing /tmp/easy_install-8zhunwcp/numpy-1.25.1/setup.cfg
Running numpy-1.25.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-8zhunwcp/numpy-1.25.1/egg-dist-tmp-8s2br4p6
Traceback (most recent call last):
File "/linaro-android/test/python-workspace/lib/python3.8/site-packages/setuptools/sandbox.py", line 156, in save_modules
yield saved
File "/linaro-android/test/python-workspace/lib/python3.8/site-packages/setuptools/sandbox.py", line 198, in …
> apk-automation: install and use python3.9

- automated/android/noninteractive-tradefed/setup.sh
- automated/android/noninteractive-tradefed/tradefed-runner.py
- automated/android/noninteractive-tradefed/tradefed.yaml
This commit change to use python3 for tradefed-runner.py,
and drop the packages installation as they will be installed
on the Ubuntu20.04 based docker image side which will have
python3 installed as the default python.
The background is that, the latest AOSP vts package needs to
have python3.8+ to run the vts_kernel_proc_file_api_test module
after the following commit:
https://android.googlesource.com/platform/test/vts-testcase/vndk/+/6f09ccb69d553a48dd231635a06889af26ff545f%5E%21/#F3
Otherwise, the following error will be reported:
```
07-26 12:45:26 I/ModuleListener: [66/67] cbe37e vts_kernel_proc_file_api_test __main__.VtsKernelProcFileApiTest#test_ProcZoneInfoTest FAILURE: Traceback (most recent call last):
File "/tmp/Soong.python_p2c4wyvb/vts_kernel_proc_file_api_test.py", line 277, …
```
> noninteractive-tradefed: change to work with python3

- automated/linux/ltp/skipfile-lkft.yaml
Clean up LTP skipfile formatting by removing unnecessary spaces and by limiting line length.
These changes will align the skipfile with the ruamel.yaml Python library's formatter, which I plan to use to for automating updates to the skipfile.
> automated: linux: ltp: skipfile: Skipfile reformat

- automated/linux/network-manager/network-manager.sh
- automated/linux/network-manager/network-manager.yaml
When restarting networking it takes some time for NM to report "full" connectivity. The delay may be longer on some boards (notably RPi4). This patch allows to configure the delay depending on the board.
> automated: linux: make network-manager delay configurable

- automated/linux/kunit/kunit.sh
This fixes a problem when certain conditions are met:
```
./kunit.sh: line 94: info_msgKernel config file not available: command not found
```
> kunit: Add missing space for printed message

- automated/linux/ltp/skipfile-lkft.yaml
Add a variable that contains a list of all boards.
When automating updates to the skipfile, it is difficult to remove single boards from a skipfile entry, as we need to know the list of boards that "all" represents.
To improve this, we can add a variable that maintains a list of all the currently supported LKFT boards. This way, when we want to remove one or more boards from a skipfile entry, we take the full list and remove the relevant boards.
> automated: linux: ltp: skipfile: Add board list

- automated/android/noninteractive-tradefed/monitor_fastboot.sh
so that it could try again after the fastboot failure
case like reported here:
https://linaro.atlassian.net/browse/STG-5007
when the usb connection to the DUT is not stable
and the wait will be done by the fastboot command
until it finds the device is in fastboot mode again.
> noninteractive-tradefed: monitor_fastboot.sh: drop sleep

- automated/linux/el2go/el2go.sh
- automated/linux/el2go/el2go.yaml
This patch adds support for testing AWS IoT integration for EL2GO service with FoundriesFactory. More detailed instructions are available from the el2go.yaml
> automated: linux: Add AWS IoT use case to el2go test

- automated/linux/ltp/skipfile-lkft.yaml
Previously the `all` keyword for boards was replaced with an list `all_boards` to store the list of supported boards to make it possible to remove boards as part of the automation for skipfile testing.
To make the commits easier to read, it has been suggested that the all_boards alias should be removed, and the list of boards should be maintained within each skipfile entry. This way when boards are removed as part of the automated skipfile testing the diff will be much easier to read. When a board is removed from an entry that previously had all boards, instead of the diff reading "all_boards" -> "\<list of all_boards with some entries removed\>" the diff will just show which boards were removed.
This will make the update commits much easier to interpret and review. Additionally, as the …
> automated: linux: ltp: skipfile-lkft: Remove the all_boards alias

- automated/linux/network-basic/network-basic.sh
When last test in network-basic fails (download-a-file) the whole set of tests is lost because LAVA receives exit code 1 and ignores the whole network-basic suite. This patch adds "exit 0" to the end of the test script to avoid this issue.
> automated: linux: fix network-basic exit code

- automated/android/noninteractive-tradefed/setup.sh
which is required by the aosp main build cts/vts now
> noninteractive-tradefed: use jdk17 for aosp-main

- automated/linux/offline-update/offline-run.sh
- automated/linux/offline-update/offline-run.yaml
- automated/linux/offline-update/offline-update.sh
- automated/linux/offline-update/offline-update.yaml
- automated/linux/offline-update/sh-lib
- automated/linux/offline-update/z-99-aklite-callback-ostree.toml
- automated/linux/offline-update/z-99-aklite-callback.toml
Offline update is a feature of LmP enabling update of devices that are offline most of the time.
> automated: linux: Add offline update test

- automated/lib/sh-test-lib
This patch adds 2 functions that deal with u-boot variables and variable comparison to sh-test-lib. These functions are used in ota-upgrade and ota-rollback tests.
> lib: add u-boot related functions to sh-test-lib

- automated/linux/ota-update/README.md
- automated/linux/ota-update/static-delta.sh
- automated/linux/ota-update/static-delta.yaml
- automated/linux/ota-update/z-99-aklite-callback-ostree.toml
- automated/linux/ota-update/z-99-aklite-callback.toml
Static delta is a variant of OTA update test. It exercises a feature of ostree that lets limit the number of downloads from ostree server by packing the objects into compressed packages. ostree server is also able to calculate the size of the whole update. This allows aktualizr-lite to reject the OTA update if it's size exceeds the threshold limits. Default threshold in aktualizr-lite is 90% disk occupancy after OTA update.
> automated: linux: ota-update add static-delta test

- automated/linux/ota-update/download-update.sh
- automated/linux/ota-update/download-update.yaml
- automated/linux/ota-update/verify-reboot.sh
- automated/linux/ota-update/verify-reboot.yaml
- automated/linux/ota-update/verify-update.sh
- automated/linux/ota-update/verify-update.yaml
This patch adds another check to OTA upgrade test. u-boot of RPMB variable is set before the upgrade. It should not be removed or altered by the upgrade process which is checked after the update.
> automated: linux: OTA upgrade u-boot variable persistence

- automated/linux/ota-rollback/download-update.sh
- automated/linux/ota-rollback/download-update.yaml
- automated/linux/ota-rollback/verify-reboot.sh
- automated/linux/ota-rollback/verify-reboot.yaml
- automated/linux/ota-rollback/verify-rollback.sh
- automated/linux/ota-rollback/verify-rollback.yaml
- automated/linux/ota-update/download-update.sh
- automated/linux/ota-update/download-update.yaml
- automated/linux/ota-update/verify-reboot.sh
- automated/linux/ota-update/verify-reboot.yaml
- automated/linux/ota-update/verify-update.sh
- automated/linux/ota-update/verify-update.yaml
This commit allows to print aktualizr-lite logs at the end of the test. DEBUG flag is turned off by default.
> automated: linux: Add debug option to OTA tests

- automated/linux/factory-reset/prepare-reset.sh
- automated/linux/factory-reset/prepare-reset.yaml
- automated/linux/ota-update/download-update.sh
- automated/linux/ota-update/download-update.yaml
This patch allows to register device to FoundriesFactory using HSM. It's enabled in ota-update and factory-reset tests. Main use case is to test registration with SE050 devices from NXP.
> automated: linux: device registration with HSM module

- .readthedocs.yml
Readthedocs build automation has a new format. This patch fixes build errors for https://test-definitions.readthedocs.io/
> Fix .readthedocs.yml file

- automated/linux/aklite-apps/aklite-apps.sh
- automated/linux/aklite-apps/aklite-apps.yaml
Test exercises aklite-apps utility from LmP. This utility allows to run docker-compose apps without registering to FoundriesFactory.
> automated: linux: add aklite-apps test

- docs/tags.md
- mkdocs.yml
- mkdocs_plugin/testdefinitionsmkdocs/__init__.py
New version of material theme and plugins breaks when there is empty "tags" stanza in the metadata section of the markdown. This patch only adds "tags" if there are any to add.
Second issue fixed is adding an empty tags.md file which is now required to present collected tags in the generated docs.
> docs: fix automated docs generation

- automated/linux/pkcs11/pkcs11.yaml
This patch changes formatting for test description to markdown. This allows it to be rendered in the readthedocs.org properly.
> automated: linux: update docs for pkcs11 test

- .github/workflows/docs.yml
- .github/workflows/test-plans-pipeline.yml
We shouldn't lock down to old python version.
> Actions: Remove python-dep

- automated/linux/kselftest/kselftest.sh
- automated/linux/kselftest/parse-output.py
The previous kselftests TAP parser has a few shortcomings that prevent it from working well with the mm kselftests output. mm kselftests are nested up to 3 levels deep, with the most important information, from the user's perspective, usually contained in the middle level. But the parser isn't nesting-aware, and instead flattens test results to include the first and last level of nesting and ignroed everything in the middle. This leads to undescriptive and confusing test names in kernelci UI.
Additionally, conflicting test names extracted by the parser are not made unique, which leads to multiple distinct tests being collapsed into a single test within the kernelci UI, and its status is set to the last occurence of the test in the list. So you might have multiple instances that fail, but …
> automated: kselftest: Rewrite parser to support nesting

- automated/linux/lmp-device-register/check_toml.py
- automated/linux/lmp-device-register/lmp-device-register.sh
This patch updates the strings matching to the current version of the software.
> automated: linux: update lmp-device-register test

- automated/android/noninteractive-tradefed/setup.sh
instead using the default version in the system,
either installed by the user manually or installed
inside some docker image, to avoid confusions caused by
unmanaged adb versions, like the "ADB server didn't ACK"
issue with the current latest adb version(platform-tools r35)
reported here:
https://lkft.validation.linaro.org/scheduler/job/7266683#L15671
> noninteractive-tradefed: stop using the latest adb

- automated/android/noninteractive-tradefed/tradefed.yaml
- automated/utils/upload-to-squad.sh
With the automated/utils/upload-to-squad.sh added and the change on the noninteractive-tradefe test as an example in this pull request. there are other tests need to be update as well after pull request.
The SQUAD url should be defined in the format like described here:
https://squad.readthedocs.io/en/latest/intro.html#submitting-results
And the job definition, SQUAD_ARCHIVE_SUBMIT_TOKEN should be defined under the secrets section.
```yaml
secrets:
SQUAD_ARCHIVE_SUBMIT_TOKEN: SQUAD_ARCHIVE_SUBMIT_TOKEN 
```
And SQUAD_UPLOAD_URL should be defined as one parameter like:
```yaml
- test:
...
definitions:
- repository: https://github.com/Linaro/test-definitions.git
from: git
path: automated/android/noninteractive-tradefed/tradefed.yaml
params:
...
SQUAD_UPLOAD_URL: …
```
> Add support to upload artifacts to SQUAD server

- automated/android/apk-automation/apk-automation.yaml
- automated/android/boottime/boottime.yaml
This will requires the merge of https://github.com/Linaro/test-definitions/pull/497
> Add uploading support for the android apk-automation and boottime tests

- automated/linux/kselftest/kselftest.sh
This patch always renames downloaded kselftest tarball to the value set in "TESTPROG". Default behaviour of the kselftest.sh script remains unchanged:
1) TESTPROG and TESTPROG_URL undefined: fall back to tarball/URL defaults
2) only TESTPROG defined: download specified test data from Linaro
3) only TESTPROG_URL defined: rename downloaded tarball to one of the defaults (based on architecture) but extract it immediately (so it's discarded anyway and the name becomes irrelevant)
4) both defined: specify name for the downloaded tarball
Case (4) is the only new branch added by this patch. Adjustments in case (3) should be transparent when running kselftest.sh script.
Fixes: #500
> automated: kselftest: explicitly set name of downloaded tarball

- automated/linux/xfstests/xfstests.sh
- automated/linux/xfstests/xfstests.yaml
xfstests is a test suite for validating the reliability and stability of file systems in the Linux kernel.
It covers a broad range of file systems, including ext4, XFS, Btrfs, and others, with tests for performance, error handling, and filesystem operations.
> linux: adding xfstests

- automated/linux/cyclicdeadline/cyclicdeadline.sh
- automated/linux/cyclicdeadline/cyclicdeadline.yaml
- automated/linux/cyclictest/cyclictest.sh
- automated/linux/cyclictest/cyclictest.yaml
- automated/linux/signaltest/signaltest.sh
- automated/linux/signaltest/signaltest.yaml
Add the feature to run a thread per CPU automatically.
This simplifies setups with many different boards where the test should run a thread per available CPU.
https://github.com/kernelci/kernelci-core/pull/2397
> preempt-rt: add support to run a thread per cpu

- automated/linux/ota-apps/switch-apps.sh
- automated/linux/ota-apps/switch-apps.yaml
This test uses external infrastructure to force app updated on FoundriesFactory registered device running LmP.
> automated: linux: add switch-apps test for LmP

- automated/linux/aklite-download-interrupt/aklite-download-interrupt.sh
This patch fixes call to lmp-device-auto-register in aklite-download-interupt tests. The script has to be called from systemd service which sets up proper variables.
> automated: linux: fix registration in aklite interrupt

- automated/linux/lmp-device-register/check_toml.py
Python libraries toml and tomllib are not API compatible. This patch switches the code to use a part of API that is the same in both libraries.
> automated: linux: fix toml parsing in lmp-device-register

- automated/linux/spectre-meltdown-checker-test/bin/spectre-meltdown-checker.sh
- automated/linux/spectre-meltdown-checker-test/spectre-meltdown-checker-test.sh
- automated/linux/spectre-meltdown-checker-test/spectre-meltdown-checker-test.yaml
Release notes for v0.46:
https://github.com/speed47/spectre-meltdown-checker/releases/tag/v0.46
> spectre-meltdown-checker: Update to v0.46

- automated/linux/ota-rollback/download-update.sh
- automated/linux/ota-rollback/download-update.yaml
This patch allows to corrupt u-boot image in arbitrary path. It's required for systems that use LUKS encryption. When LUKS is used, after downloading an update, bootloader files are copied to unencrypted partition, from where they can be read by u-boot runtime.
> automated: linux: enable custom path for OTA rollback u-boot

- automated/linux/ota-update/download-update.sh
- automated/linux/ota-update/verify-reboot.sh
- automated/linux/ota-update/verify-update.sh
This patch allows to set empty u-boot custom variable name. This will prevent the test script from attempting to set the variable during the test. It is important for boards that use RPMB with only a list of allowed variables.
> automated: linux: allow disabling custom variable in ota-update

- automated/linux/ltp/ltp.sh
- automated/linux/ltp/ltp.yaml
LTP has depricated their runltp runner to run tests. The new one is called kirk
(https://github.com/linux-test-project/kirk.git) which replaces runltp. For now runltp will be the default runner. If someone wants to use kirk, it has to be pre-installed into the rootfs, and the yaml varialbe RUNNER has to be set to 'kirk' or '/usr/local/bin/kirk'.
> automated: linux: ltp: add support for the new kirk runner

- automated/linux/kselftest/kselftest.sh
- automated/linux/kselftest/kselftest.yaml
Currently we are not able to run the subtests of a kselftest due to lack of support for passing the parameters to the test case. Hence, solve this problem by adding support for passing environment variables in KernelCI kselftest.
> kselftest: Add new option -E for specifying environment variables

- automated/linux/docker/docker.sh
This patch enables "hello-world" image testing from Amazon mirror. It's required for cases where hub.docker.com is not available.
> automated: linux: support hello-world docker image from mirrors

- automated/linux/modules/modules.sh
- automated/linux/modules/modules.yaml
Test to load/unload modules multiple times to see if something bad happens, which it shouldn't.
The majority of drivers registers themselves to an API that calls back into the driver when the hardware side (or network protocol, file system, etc) is getting detected or requested.
Loading and unloading modules that the DUT don't have hardware for is likely to find more of the obvious bugs.
> add module testing

- automated/linux/modules/modules.sh
- automated/linux/modules/modules.yaml
Make it possible to skip problematic modules that is known to fail.
> automated: linux: modules: add SKIPLIST

- automated/linux/lmp-device-register/lmp-device-register.sh
Backend error message has changed and the test no longer matches the proper string. This patch fixes the issue
> automated: linux: fix lmp-device register error message matching

- automated/linux/rtla/parse_rtla.py
- automated/linux/rtla/rtla-osnoise.sh
- automated/linux/rtla/rtla-timerlat.sh
The rtla tool puts out starting with the "ALL:" line a summary. This
confused the parser and we only report per thread/cpu anyway. So just
ignore it.
Signed-off-by: Daniel Wagner <wagi@monom.org>
Fixes: https://github.com/Linaro/test-definitions/issues/530
> automated: linux: rtla: ignore summary info

- automated/android/noninteractive-tradefed/tradefed.sh
- automated/android/noninteractive-tradefed/tradefed.yaml
For some cases that before the WIFI or ethernet features work on the board,
it would be better to be able to run the cts/vts tests for such devboards too,
regardless of the network related failures.
So adding the INTERNET_ACCESS variable to specify
it it's necessary for the test, default to true
for backwards compatibility
> noninteractive-tradefed: enable skipping of internet access check

- automated/android/noninteractive-tradefed/tradefed.sh
it should be OR (||) instead of AND(&&) for the true and True check.
> noninteractive-tradefed: fix logic of INTERNET_ACCESS check

- automated/linux/video/Dockerfile
- automated/linux/video/compare.py
- automated/linux/video/requirements.txt
- automated/linux/video/video.sh
- automated/linux/video/video.yaml
The test takes a screenshot from video output and compares to the reference image. It is intended to test HDMI output from DUT.
> automated: linux: add video output comparison test

- automated/linux/xfstests/xfstests.sh
The result output doesn't drop '.notrun', '.out.bad' and '.full' from the test name so it looks like 'brtf-006.notrun skip' and the sed cmdline assumes that '.notrun' is at the end of the row, which it were before it got reformated.  When dropping the '$' from sed cmdline it works as expected.
> automated: linux: xfstests: fix result output

- automated/linux/gpiod/parse-output.py
The output of the test name always starts with a '_' which is wrong. Removing that by remove the prefixed '{tests}_' the testname, and the 'tests' variable was assigned to an empty string. This resulted in that the testname started with a prefix '_'.
> automated: linux: gpiod: parse-output: drop 'tests' prefix

- automated/linux/alsa-smoke/alsa-smoke.sh
- automated/linux/alsa-smoke/alsa-smoke.yaml
The test uses alsa-utils tools aplay and arecord to find whether any playback and record devices are available in the system. If the test runs on an OS without package manager and no alsa-utils available it will fall back to look for character devices named "controlCX" where X is a number. This is the same approach that alsa-utils uses. The default path to look for devices is /dev/snd/
> automated: linux: add alsa-smoke test

- automated/lib/py_util_lib.py
- automated/utils/test-runner.py
distutils package was removed from python3.12. This patch removes distutils from test-runner and replaces it with shutil.
> automated: utils: remove distutils from test-runner

- automated/utils/upload-to-squad.sh
instead of the "Auth-Token" way as suggested here:
https://squad.readthedocs.io/en/latest/intro.html#submitting-results
Reported-by: Benjamin Copeland <benjamin.copeland@linaro.org>
> upload-to-squad.sh: use "Authorization" in header for uploading

- automated/linux/ltp/ltp.sh
When running multiple ltp suites without rebooting, the following error is shown when running kirk the second time:
'kirk: error: JSON report file already exists: /tmp/kirk-report.json'
Remove the kirk-report.json file after parsing the file.
> automated: linux: ltp: remove kirk's report.json after parsing it

- automated/android/noninteractive-tradefed/setup.sh
The java path on aarch64 is something like
/usr/lib/jvm/java-11-openjdk-arm64/bin/java
which is different from the path on x86_64 like
/usr/lib/jvm/java-11-openjdk-amd64/bin/java
change to use differnt paths for different architectures
accordingly to support the aarch64 host as well.
> noninteractive-tradefed: add java path support for aarch64

- automated/linux/kselftest/parse-output.py
In kselftest/parse-output.py a change made for debugging was mistakenly added in a previous commit, which is causing kselftest to not properly create and find extended error log files.
Removes faulty code.
> automated: linux: kselftest: fix kselftest log publish

- automated/linux/ltp/ltp.sh
- automated/utils/send-to-lava.sh
See individual commit descriptions for motivation
> ltp: improve handling of test case logs

- automated/linux/alsa-bat/bat.sh
- automated/linux/alsa-bat/bat.yaml
This is an incredibly basic test, shipped as part of alsa-utils, which
plays and records a tone then uses a FFT to verify that the tone appears
sufficiently cleanly in the output.  It requires that the system under
test have previously been set up with a loopback audio path, either
within the card or via cables.
> automated: linux: Add ALSA basic audio test

- automated/android/noninteractive-tradefed/tradefed.sh
After the following lava change:
https://gitlab.com/lava/lava/-/merge_requests/2734
the kisscache url is exported by LAVA via the HTTP_CACHE variable, it's better to check and use the varible in the scripts as well, to avoid being passed from the LAVA job definition.
> noninteractive-tradefed: using HTTP_CACHE to get kisscache url

- automated/utils/send-to-lava.sh
This avoids losing signals if they happen to coincide with kernel messages.
> send-to-lava: respect KMSG if set by the job definition

- automated/linux/ltp/ltp.sh
- automated/linux/ltp/ltp.yaml
Add support for parallel test execution with the new LTP test runner, kirk.  This update introduces the KIRK_WORKERS variable, which allows you to configure the number of worker processes used for running tests in parallel. This can significantly reduce test runtime on systems with many CPU cores.
Suggested-by: Mark Brown <broonie@kernel.org>
> automated: linux: ltp: kirk runner: parallelize tests

- automated/linux/cyclicdeadline/cyclicdeadline.sh
- automated/linux/cyclicdeadline/cyclicdeadline.yaml
- automated/linux/pi-stress/pi-stress.sh
- automated/linux/pi-stress/pi-stress.yaml
This pull request introduces enhancements to the rt-tests suite by adding generic pass/fail logic to the following tests: cyclicdeadline, pi_stress.
Key Changes:
* Generic Pass/Fail Logic: A standardized evaluation mechanism has been implemented to determine test success or failure based on a predefined threshold (PTHRESHOLD, expressed in percent).
* Improved Result Reporting: Output now clearly indicates whether a test has passed or failed, while also preserving the original test output. This makes it easier to analyze test behavior and detect anomalies or regressions.
> Add generic pass/fail logic to rt-tests: cyclicdeadline, pi_stress

- automated/lib/sh-test-lib
- automated/linux/docker-networking/docker-networking.sh
- automated/linux/docker-networking/docker-networking.yaml
Add "host" and "none" network options to docker-networking tests. This allows to cover all simple possibilities when it comes to docker networking. All tests can be executed in one run by adding -n option to the script invocation. Example:
docker-networking.sh -n "bridge host"
Test names were appended with ${NETWORK} to indicate which network type is tested. Default is "bridge".
> automated: linux: add more options to docker networking

- automated/linux/tcpreplay/pcap/generate_pcap.py
- automated/linux/tcpreplay/tcpreplay.py
- automated/linux/tcpreplay/tcpreplay.yaml
This patch introduces an automated testing setup for tcpreplay-based traffic replay and analysis. The system consists of:
1. `tcpreplay.py`: A test runner that:
- Creates and configures a TAP interface
- Replays PCAP files using `tcpreplay`
- Tracks results and produces a summary for each test
- Handles both expected and unexpected results (e.g., xfail -> pass)
2. `generate_pcap.py`: A Scapy-based script to:
- Generate a suite of PCAP files for functional and edge case testing
- Include both valid packets and malformed/false-positive scenarios
- Provide coverage for multiple protocols (TCP, UDP, ICMP, DNS, etc.)
- Simulate problematic flows like fragmented packets and invalid flags
Highlights:
- xfail support: tests expected to fail are counted as 'pass' if they do fail
- xpass detection: …
> automated: linux: add tcpreplay testing framework

- automated/linux/ltp/ltp.sh
Currently the number of kirk workers has to be configured explicitly,
kirk itself does not support detecting the number of CPUs the system has
and test-definitions just passes the value it has straight through to
the kirk runner.  This is a bit annoying when using templating to share
job definitions over multiple device types, requiring explicit per type
configuration.
Given that a very common case is going to be to use all the CPUs
available on the target platform provide support for the magic number of
workers "max" which counts the number of CPUs reported by /proc/cpuinfo
and uses that as the number of workers.
> automated: linux: ltp: Allow detection of the number of CPUs at runtime

- automated/utils/send-to-lava.sh
When send-to-lava.sh is used with lava-test-case absent the strings generated in the script were not matching expected LAVA patterns. This patch fixes the pattern and moves the output to signal() function to respect KMSG setting in the lava-test-shell.
> automated: utils: use LAVA_SIGNAL in send-to-lava.sh

- .github/workflows/zstd-release.yml
Remove --prefix=test-definitions/ from git archive to create cleaner tar.zst archives without the directory wrapper.
LAVA assumes you don't have the directory wrapper.
> github: workflows: remove test-definitions prefix from zstd-release archives

- automated/linux/torizon/integration-tests.yaml
Add missing ssh env vars to params so they could be found on lava integration test jobs
> fix: add ssh variables to def params

- automated/linux/kvm-unit-tests/parse-output.py
This updates parse-output.py in kvm-unit-tests to output log files for each failure which include a log snippet associated with the test name.
> automated: linux: kvm-unit-tests: add errors to parse-output

- automated/linux/torizon/ostree-upgrade-tests.sh
We support both laa-qemu and laa as ostree references when searching for the target upgrade version
> Replace hard-coded value of OSTREE_REF with existing variable
