- .gitreview
> Remove .gitreview

- .gitignore
- .travis.yml
> Add Travis CI

- .travis.yml
- sanity-check.sh
- validate.py
* Use 'git diff --name-only HEAD~1' to list changed files
* Add instructions on the installation of a specific version shellcheck
* Add descriptions for the skipped pycodestyle and shellcheck codes
> Improve sanity check

- automated/doc/test-writing-guidelines.rst
> doc: fix rst list and block syntax

- automated/android/noninteractive-tradefed/tradefed.yaml
- automated/android/tradefed/tradefed.yaml
> tradefed: fix comparison for case sensitive "True" value

- automated/linux/ltp/skipfile-lkft.yaml
> LTP: skipping memory mtest06 and ksm01

- automated/android/noninteractive-tradefed/monitor_adb.sh
- automated/android/noninteractive-tradefed/setup.sh
- automated/android/noninteractive-tradefed/tradefed.yaml
> noninteractive-tradefed: add more debug

- automated/linux/fuego-multinode/boards/generic-arm64.board
- automated/linux/fuego-multinode/boards/generic-armhf.board
- automated/linux/fuego-multinode/boards/generic-x86_64.board
- automated/linux/fuego-multinode/fuego-dut.yaml
- automated/linux/fuego-multinode/fuego-host.yaml
- automated/linux/fuego-multinode/fuego.sh
- automated/linux/fuego-multinode/parser.py
- automated/linux/fuego-multinode/setup-openssh-server.sh
LAVA job example: https://lava.slipslow.ml/scheduler/job/119
> linux: add fuego multinode

- automated/doc/test-writing-guidelines.rst
- automated/linux/dockerized-tests/README.MD
> doc: a few fixes

- automated/linux/kselftest/skipfile-lkft.yaml
- automated/linux/ltp/skipfile-lkft.yaml
> LTP and kselftests: Adding stable rc 5.0 branch in skipfiles

- validate.py
> sanity-check: print installation tips when required module not installed

- automated/linux/v4l2/v4l2-compliance.sh
Fixing results parser for v4l2-compliance test.
> v4l2-compliance: results parser fix up

- automated/linux/gpiod/gpiod.sh
- automated/linux/gpiod/gpiod.yaml
> automated/linux: add new test gpiod

- automated/linux/fuego-multinode/README.MD
> linux/fuego-multinode: add readme.md

- automated/linux/ltp/ltp.sh
- automated/linux/ltp/ltp.yaml
> ltp: add a variable for LTP_TMPDIR

- automated/linux/ssuite/ssuite-bench.yaml
> ssuite: add SKIP_INSTALL variable

- automated/linux/ssuite/run-bench.sh
- automated/linux/ssuite/ssuite-bench.yaml
Signed-off-by: Paolo Valente <paolo.valente@linaro.org>
> ssuite: add only-reads option

- automated/linux/kvm-unit-tests/kvm-unit-tests.sh
- automated/linux/kvm-unit-tests/kvm-unit-tests.yaml
> kvm-unit-test: Adding kvm unit tests

- automated/linux/ssuite/ssuite-bench.yaml
> ssuite: pass in S_PATH to run-bench.sh

- automated/linux/bootrr/bootrr.yaml
> linux: add test definition for bootrr

- CODEOWNERS
Remove myself from CODEOWNERS as I am not maintaining the project.
Signed-off-by: Chase Qi <chase.qiyc@gmail.com>
> Remove chase-qi from CODEOWNERS

- automated/linux/gpiod/gpiod.sh
> automated: gpiod: remove prefix '-'

- automated/linux/kvm-unit-tests/kvm-unit-tests.sh
> kvm-unit-tests: Adding verbose output while running run_tests.sh

- automated/linux/kselftest/skipfile-lkft.yaml
- automated/linux/ltp/skipfile-lkft.yaml
> skipfile-lkft: updating ltp and kselftest skiplist

- automated/lib/android-multinode-test-lib
- automated/lib/android-test-lib
This increases the robustness in Android and MultiNode tests related to network address detection and detection of local adb devices.
> Android and multinode robustness

- automated/utils/test-runner.py
> test-runner: fix missing variable in the script

- automated/android/microbenchmarks/microbenchmarks.sh
> microbenchmarks: switch to official post-build-reports

- automated/linux/kselftest/skipfile-lkft.yaml
> kselftest: Adding branch 5.2 for skip ftracetest

- automated/android/microbenchmarks/microbenchmarks.sh
> microbenchmarks: add support for uploading to qa-reports

- automated/linux/kernel-config-checker/kernel-config-checker.sh
LKFTs config file are located /proc/config.gz added support for checking that.
> Kernel config checker

- automated/linux/spectre-meltdown-checker-test/bin/spectre-meltdown-checker.sh
- automated/linux/spectre-meltdown-checker-test/spectre-meltdown-checker-test.sh
- automated/linux/spectre-meltdown-checker-test/spectre-meltdown-checker-test.yaml
Signed-off-by: Nobuhiro Iwamatsu <nobuhiro1.iwamatsu@toshiba.co.jp>
> spectre-meltdown-checker: Update to 0.42

- automated/linux/meminfo/meminfo.sh
- automated/linux/meminfo/meminfo.yaml
Add a new test based on automated/android/meminfo,
but remove the Android specific parts.
> meminfo: add new test

- automated/android/apk-automation/gearses2eclair.py
> automated/android: close popup when running Gears

- automated/linux/kselftest/skipfile-lkft.yaml
> kselftest: skip proc-pid-vm tests

- automated/linux/fwts/fwts.sh
- automated/linux/fwts/fwts.yaml
Co-developed-by: Naresh Kamboju <naresh.kamboju@linaro.org>
> add firmware tests (fwts)

- automated/linux/igt/igt-chamelium-test.sh
1. Pass test list directory through shell environment variable IGT_TEST_ROOT
2. New run-tests.sh needs '-p' to run the tests with piglit
> igt: update igt-chamelium-test.sh

- automated/linux/ltp/skipfile-lkft.yaml
> LTP: Adding nxp-ls2088 device to known skiplist

- automated/linux/kselftest/skipfile-lkft.yaml
> kselftests: Adding nxp-ls2088 device to known skiplist

- automated/linux/kvm-unit-tests/kvm-unit-tests.sh
> automated: linux. kvm-unit-tests: check if GIT_REF

- automated/linux/armnn-benchmarks/armnn-mlperf.sh
> automated: armnn-benchmarks: fix getopts parameters

- .gitignore
- .readthedocs.yml
- docs/index.md
- docs/test-writing-guidelines.md
- mkdocs.yml
- mkdocs_plugin/requirements.txt
- mkdocs_plugin/setup.py
- mkdocs_plugin/testdefinitionsmkdocs/__init__.py
The documentation is based on mkdocs. This commit contains plugin that
creates a documentation page for each YAML file in this repository. The
file needs to follow the schema and include all metadata fields.
> docs: autogenerate documentation from YAML files

- automated/linux/ssuite/run-bench.sh
- automated/linux/ssuite/ssuite-bench.yaml
Improve number of repetitions and result description
> Improve number of repetitions and result description

- automated/linux/iperf/lava-multinode-job-example-iperf.yaml
> automated: iperf: add 'essential' role to example

- automated/android/boottime/boottime.sh
- automated/android/boottime/boottime.yaml
Signed-off-by: Vishal Bhoj <vishal.bhoj@linaro.org>
> record boot to ui result

- automated/linux/armnn-benchmarks/armnn-benchmarking.yaml
Removing space in test definition name.
> Updating armnn-benchmarking.yaml

- validate.py
> validate: add check for whitespace in metadata name

- docs/extra.css
- docs/index.md
- mkdocs.yml
- mkdocs_plugin/setup.py
- mkdocs_plugin/testdefinitionsmkdocs/__init__.py
> docs: generate table containing all tests

- automated/linux/ssuite/ssuite-bench.yaml
> automated: linux: fix description of ssuite test

- automated/linux/ltp/skipfile-lkft.yaml
> LKFT: LTP: skip fanotify09 on 4.4 and 4.9 branches

- automated/utils/requirements.txt
- automated/utils/test-runner.py
Signed-off-by: Vishal Bhoj <vishal.bhoj@linaro.org>
> Initial support to submit results to qa-reports

- automated/linux/android-platform-tools/install.sh
> automated: linux: add multiarch support to android platform tools

- automated/linux/ltp/skipfile-lkft.yaml
> LTP: skip long running memcg_stress test

- automated/linux/armnn/armnn-unit-tests.sh
> automated: linux: armnn: fix shellchecks

- plans/testplan2html.py
> plans: support 'branch' checkout in testplan2html

- automated/android/apk-automation/andebenchpro2015.py
- automated/android/apk-automation/antutu6.py
- automated/android/apk-automation/apk-automation.sh
- automated/android/apk-automation/apk-automation.yaml
- automated/android/apk-automation/benchmarkpi.py
- automated/android/apk-automation/caffeinemark.py
- automated/android/apk-automation/cf-bench.py
- automated/android/apk-automation/common/__init__.py
- automated/android/apk-automation/glbenchmark25.py
- automated/android/apk-automation/jbench.py
- automated/android/apk-automation/linpack.py
- automated/android/apk-automation/main.py
- automated/android/apk-automation/quadrantpro.py
- automated/android/apk-automation/scimark.py
- automated/android/apk-automation/vellamo3.py
Tested locally with hikey960 aosp-master-throttled-copped#6640860 build
> apk-automation: update to work with aosp master branch

- automated/linux/kvm-unit-tests/kvm-unit-tests.sh
kvm-unit-tests: update kvm-unit-tests repo link
> kvm-unit-tests: update kvm-unit-tests repo link

- automated/linux/kselftest/skipfile-lkft.yaml
> linux: kselftest: skipfile-lkft: Add new branch linux-5.8.y

- automated/linux/lemp/debian-nginx.conf
- automated/linux/lemp/lemp.sh
Signed-off-by: Vishal Bhoj <vishal.bhoj@linaro.org>
> fix lemp test on debian

- automated/linux/hci-smoke/hci-smoke-test.sh
- automated/linux/wlan-smoke/wlan-smoke-test.sh
> automated/linux: {hci, wlan}-smoke fixes

- automated/android/apk-automation/gearses2eclair.py
to make the code a bit easy to read, and could work with python3
> gearses2eclair.py: use regular expression to find the result line

- automated/linux/kselftest/kselftest.sh
Instead of hard-coding "tar.gz", use "tar -xaf" to detect the extension
and do the right thing. Closes #195.
Signed-off-by: Kees Cook <keescook@chromium.org>
> kselftest: Compression-agnostic fetching

- automated/android/noninteractive-tradefed/tradefed.yaml
so that we could see where the error is reported easily
Change-Id: I352ece5a6c63ab1ed20cf4712d1e5a98978fda17
> tradefed.yaml: update the adb lost message to show tradefed tag as well

- plans/testplan2html.py
- add date to metadata
- fix conversion from HEAD to sha1
- use the template name for the output file
Signed-off-by: Nicolas Dechesne <nicolas.dechesne@linaro.org>
> plans: fix issues with testplan2html

- automated/lib/sh-test-lib
- automated/linux/crypto/crypto.sh
- automated/linux/crypto/crypto.yaml
Implement a simple crypto testsuite which try to loads all crypto
algorithm and so force selftests to run.
This test suite will check for errors and then a pass/fail will be assigned for each crypto algorithm.
> crypto: basic tests

- automated/linux/rteval/rteval.sh
- automated/linux/rteval/rteval.yaml
> add rteval suite

- automated/linux/igt/igt-test.sh
Some test results were overridden to dmesg-warn/dmesg-fail, due to some
kernel messages. These test results were not recognized by LAVA.
To avoid it, we can run tests through igt_runner with "--dmesg-warn-level 0"
argument.
> igt: run tests through igt_runner to avoid dmesg-warn

- automated/linux/rteval/rteval.sh
- automated/linux/rteval/rteval.yaml
> rteval: fix TEST_GIT_URL bug

- automated/linux/igt/print-test-result.py
Process the test result log with UTF-8 encoding
> igt: process test result log with UTF-8 encoding

- automated/linux/deqp-runner/deqp-runner.sh
> automated/linux/deqp-runner: Remove unneeded quotes in deqp-runner

- automated/linux/igt/igt-test.yaml
1. Remove command which is used to delete Chamelium logs
2. Force python to use utf-8 for stdout/stderr encoding
> Igt tuning

- automated/android/noninteractive-tradefed/tradefed.sh
- automated/android/noninteractive-tradefed/tradefed.yaml
> android: fix potential issue in tradefed debug message

- automated/linux/ml-bench/tvm-bench.sh
- automated/linux/ml-bench/tvm-bench.yaml
Creating files for ml-bench, an implementation of various ml frameworks to be deployed to devices in the lab.
> ml-bench creation

- automated/linux/kselftest/skipfile-lkft.yaml
> selftests: vm: run_vmtests hangs on arm64

- automated/linux/fwts/fwts.sh
> fwts: improve results parser

- automated/linux/fwts/fwts.sh
- automated/linux/fwts/fwts.yaml
> automated: linux: fwts: filter out x86 tests on other archs

- automated/linux/kselftest/skipfile-lkft.yaml
> kselftest: skipfile: Adding branch 5.10

- automated/linux/ltp/ltp.sh
Also add missing quotes around variable.
> ltp: allow to pass skipfile as absolute path

- automated/linux/ssuite/run-bench.sh
Fixes: ce20d323206f ("ssuite: update to use the common git clone of the test")
> ssuite: run-bench: fix S_PATH to TEST_DIR

- automated/linux/kselftest/skipfile-lkft.yaml
> kselftest: Adding new stable-rc 5.11 branch

- automated/linux/ostree/ostree.sh
- automated/linux/ostree/ostree.yaml
> automated: linux: Add ostree test

- automated/linux/docker-networking/docker-networking.sh
- automated/linux/docker-networking/docker-networking.yaml
> automated: linux: add docker-networking test

- automated/linux/ima/ima.sh
- automated/linux/ima/ima.yaml
- automated/linux/kernel-config-checker/kernel-config-checker.sh
- automated/linux/kernel-config-checker/kernel-config-lib
> automated: linux: add IMA smoke test

- automated/linux/kselftest/skipfile-lkft.yaml
> kselftests: Skipping hang test case kvm get-reg-list

- automated/linux/hci-smoke/hci-smoke-test.sh
- automated/linux/hci-smoke/hci-smoke.yaml
> automated: linux: add lescan to hci-smoke

- automated/linux/ltp-open-posix/ltp-open-posix.sh
- automated/linux/ltp-open-posix/ltp-open-posix.yaml
Run specific group test from ltp-open-posix. Parse the
results and send it to lava-test-case.
Signed-off-by: lakshmipathi ganapathi <lakshmipathi.ganapathi@collabora.com>
> LTP: Update ltp-open-posix to run specific group test

- automated/lib/sh-test-lib
- automated/linux/gpiod/gpiod.sh
Check if debugfs is mounted, if not try to mount it or exit
> Gpiod check debugfs

- automated/utils/test-runner.py
fiotest is a test runner/executor that works on Foundries.io LmP in a
docker container. More details in the repository:
https://github.com/foundriesio/fiotest
> test-runner: Add support for reporting to fiotest

- automated/linux/ima/ima.sh
> automated: fix IMA test when IMA is not enabled

- automated/linux/wlan-download/wlan-download-test.sh
This patch fixes the issue with wlan-download test when it's used on
busybox like environment. When dhclient is not available there is a
chance it can be replaced with udhcpc.
> automated: add support for udhcpc in wlan-download test

- automated/linux/spectre-meltdown-checker-test/bin/spectre-meltdown-checker.sh
- automated/linux/spectre-meltdown-checker-test/spectre-meltdown-checker-test.sh
- automated/linux/spectre-meltdown-checker-test/spectre-meltdown-checker-test.yaml
Signed-off-by: Alice Ferrazzi <alice.ferrazzi@miraclelinux.com>
> spectre-meltdown-checker: Update to 0.44

- automated/linux/kselftest/skipfile-lkft.yaml
- automated/linux/ltp/skipfile-lkft.yaml
Adding new device type dragonboard-845c to LTP and kselftest.
> skipfile: Adding new device type dragonboard-845c

- automated/linux/aklite-download-interrupt/aklite-callback.sh
- automated/linux/aklite-download-interrupt/aklite-download-confirm.sh
- automated/linux/aklite-download-interrupt/aklite-download-confirm.yaml
- automated/linux/aklite-download-interrupt/aklite-download-interrupt.sh
- automated/linux/aklite-download-interrupt/aklite-download-interrupt.yaml
- automated/linux/aklite-download-interrupt/aklite-download-resume.sh
- automated/linux/aklite-download-interrupt/aklite-download-resume.yaml
- automated/linux/aklite-download-interrupt/z-99-aklite-callback.toml
- automated/linux/aklite/aklite.sh
- automated/linux/aklite/aklite.yaml
- automated/linux/disable-aklite-reboot/disable-aklite-reboot.sh
- automated/linux/disable-aklite-reboot/disable-aklite-reboot.yaml
- automated/linux/disable-aklite-reboot/z-99-aklite-callback.toml
- automated/linux/ota-rollback/aklite-callback.sh
- automated/linux/ota-rollback/download-update.sh
- automated/linux/ota-rollback/download-update.yaml
- automated/linux/ota-rollback/sh-lib
- automated/linux/ota-rollback/verify-reboot.sh
- automated/linux/ota-rollback/verify-reboot.yaml
- automated/linux/ota-rollback/verify-rollback.sh
- automated/linux/ota-rollback/verify-rollback.yaml
- automated/linux/ota-rollback/z-99-aklite-callback.toml
- plans/foundries-manufacturing-test-plan.yaml
This patch series contains set of tests used to test Foundries.io Linux microPlatform. It focuses on the OS features - mainly aktualizr-lite daemon. The daemon is used to handle OTA software updates.
> Foundriesio test cases

- automated/android/apk-automation/andebenchpro2015.py
- automated/android/apk-automation/antutu6.py
- automated/android/apk-automation/benchmarkpi.py
- automated/android/apk-automation/caffeinemark.py
- automated/android/apk-automation/cf-bench.py
- automated/android/apk-automation/gearses2eclair.py
- automated/android/apk-automation/geekbench4.py
- automated/android/apk-automation/glbenchmark25.py
- automated/android/apk-automation/javawhetstone.py
- automated/android/apk-automation/jbench.py
- automated/android/apk-automation/linpack.py
- automated/android/apk-automation/quadrantpro.py
- automated/android/apk-automation/rl-sqlite.py
- automated/android/apk-automation/scimark.py
- automated/android/apk-automation/vellamo3.py
- automated/linux/kvm/wait-ip.py
- automated/linux/ota-update/ota-update.py
- automated/linux/ui-browser-test/robot-results-parser.py
Black version 22.1.0 dropped Python 2 support. So we need to update our
sources.  Python3 requires you to write the print function with
parentheses.
> fix sanity checks: update print to python3

- manual/generic/linux/network-basic.yaml
- manual/generic/linux/network-manager.yaml
- manual/generic/linux/ota-rollback.yaml
- manual/generic/linux/ota-update.yaml
- plans/foundries-manufacturing-test-plan.yaml
Manual test plans mirroring automatic basic tests for use with test-runner. 
Fix for incorrect parameter set in automatic manufacturing scenario test plan.
> Manual manufacturing2

- automated/utils/test-runner.py
When executing tests with test-runner a copy of test-definitions
repository is created. This copy is not removed after tests are
complete. When running repeated tests in the same environment this leads
to filling up the storage. This patch prevents the problem by removing
the copy of test-definitions along with other temporary files after
tests were executed. The downside is that all the results and logs are
removed as well. Therfore the --cleanup option should only be used when
using external test result repository (like LAVA or SQUAD). The option
is disabled by default.
> automated: test-runner: cleanup repository copy

- automated/linux/aklite/aklite.sh
> automated: linux: fix typo in aklite test

- plans/foundries-manufacturing-test-plan.yaml
Removed duplicated test and fixed typo in the parameters
> plans: fix foundries.io test-plan

- automated/android/apk-automation/apk-automation.sh
There are some syntax errors reported now with the Bionic LXC method.
https://validation.linaro.org/scheduler/job/2815047#L6685
In the future, we will update to use the docker method,
with newer ubuntu version docker image
> apk-automation.sh: update to use the python3 to workaround with Bionic

- automated/linux/ota-rollback/download-update.yaml
- automated/linux/ota-rollback/verify-reboot.yaml
- automated/linux/ota-rollback/verify-rollback.yaml
> automated: linux: fix path in ota-rollback test

- manual/foundries/aklite-full-disk.yaml
> manual: add aktualizr-lite full disk test

- validate.py
> validate: fix typo in metadata validation

- automated/linux/aklite-download-interrupt/aklite-download-interrupt.sh
> automated: linux: remove more objects in aklite-interrupt

- automated/linux/wireguard-fioconfig/wg-pk.sh
- automated/linux/wireguard-fioconfig/wg-pk.yaml
Signed-off-by: Brendan Wood <brendan.wood@foundries.io>
>  automated: linux: wireguard fioconfig test

- automated/linux/pkcs11/pkcs11.sh
> automated: linux: fix library name in pkcs11 test

- automated/linux/pkcs11/pkcs11.sh
When testing RSA cert creation in a loop, the object removal part was
wrong. The certs were not removed after the test. Also the check for
number of certificates left gave incorrect result. This patch fixes both
issued. Minor issues with SE05X session was also fixed.
> automated: linux: fix test condition on pkcs11

- automated/linux/el2go/el2go.sh
- automated/linux/el2go/el2go.yaml
- automated/linux/el2go/z-99-el2go.toml
> automated: linux: add EL2GO test

- automated/android/noninteractive-tradefed/tradefed.sh
to workaround the problem reported here:
https://linaro.atlassian.net/browse/STG-3756
> tradefed.sh: pass --no-cache to wget

- automated/linux/secure-boot/secure-boot-enabled.sh
- automated/linux/secure-boot/secure-boot-enabled.yaml
Validate Secure Boot is enabled.
> Add Secure Boot Enabled definition

- automated/linux/pkcs11/pkcs11.sh
When running loop test in pkcs11, TA may run out of memory. This isn't a recoverable error and the remaining results should not be trusted. This patch adds a check which indicates OOM situation with a proper test result. It allows to diagnose the problem manually afterwards.
> automated: linux: add more pkcs11 tests

- automated/linux/ota-update/verify-update.sh
> automated: linux: Wait for aklite to start in ota-upgrade

- automated/linux/ota-rollback/download-update.sh
- automated/linux/ota-rollback/verify-rollback.sh
Verify successful rollback after OTA upgrade containing corrupt docker app.
Signed-off-by: Brendan Wood <brendan.wood@foundries.io>
> automated: linux: add docker-corrupt OTA test

- automated/linux/pkcs11/pkcs11.sh
- automated/linux/pkcs11/pkcs11.yaml
This set of patches adds capability to test sign/verify during OTA process.
It also refactors the code and fixes other minor mistakes.
> automated: pkcs11 ota verify

- automated/linux/docker-prune/aklite-callback.sh
- automated/linux/docker-prune/disable-prune.sh
- automated/linux/docker-prune/disable-prune.yaml
- automated/linux/docker-prune/prune-lib.sh
- automated/linux/docker-prune/prune.sh
- automated/linux/docker-prune/prune.yaml
- automated/linux/docker-prune/z-99-aklite-callback.toml
Tests that check whether docker correctly prunes
app images after update or disable
> Add docker-prune tests

- automated/android/noninteractive-tradefed/tradefed.yaml
which seems not updated in the pull request
> Android: noninteractive-tradefed: fix the network failure message

- automated/linux/gpiod/gpiod.sh
- automated/linux/gpiod/parse-output.py
update the log parser for gpiod to produce LAVA pass/fail output.
from:
ok <number> <testcase>
To:
<testcase> pass
> linux: gpiod: add a parser

- automated/linux/ota-update/static-delta.sh
When updating the device using static deltas, the test script has to wait for aktualizr-lite to complete installation before rebooting.
When there is no static detla available, the test job should end as incomplete.
This patch also changes how the aklite signal is checked to align with other OTA testing scripts.
> automated: linux: fix issues with static-delta OTA update

- automated/linux/aklite-apps/aklite-apps.sh
- automated/linux/aklite-apps/aklite-apps.yaml
- automated/linux/aklite-apps/apps-early-start.sh
- automated/linux/aklite-apps/apps-early-start.yaml
> Apps early start

- automated/linux/systemd-analyze/systemd-analyze.sh
- automated/linux/systemd-analyze/systemd-analyze.yaml
Add systemd-analyze to analyze the different boot times, firmware, bootloader, kernel and userspace.
> automated: linux: add systemd-analyze

- automated/linux/systemd-analyze/systemd-analyze.yaml
Update the yaml description.
Reported-by: Benjamin Copeland <benjamin.copeland@linaro.org>
> automated: linux: systemd-analyze: update description

- automated/linux/libhugetlbfs/libhugetlbfs.sh
- automated/linux/libhugetlbfs/libhugetlbfs.yaml
Make it possible to use prebuilt libhugetlbfs overlays.
> automated: linux: libhugetlbfs: use prebuilt overlays

- automated/linux/modules/modules.sh
fix indentation, and don't use the command "find" to find the modules look in modules.order.
This will make the order of the modules more predictable.
> Fix modules

- automated/android/noninteractive-tradefed/tradefed.sh
noninteractive-tradefed: improvement on network check
The improvements are using top variables, reporting dns failures
separately, and adding some more meaningful debug output,
as well as the output of ifconfig command. Move all the internet access
into a function named check_internet_access().
Suggested-by: Anders Roxell <anders.roxell@linaro.org>
Suggested-by: Benjamin Copeland <benjamin.copeland@linaro.org>
> noninteractive-tradefed: improvement on network check

- automated/utils/upload-to-squad.sh
> upload-to-squad.sh: add retry to help success rate for uploading

- automated/linux/kselftest/parse-output.py
Currently kselftest logs for failures aren't displaying full logs.
This change creates log files for each failure and tracks the results.
Forks changes to send-to-lava from PR #552 .
> automated: linux: kselftest: publish kselftest failure logs

- automated/android/kunit/kunit.sh
- automated/android/kunit/kunit.yaml
with the tests.zip package provided, which is generated by the normal gki kernel build
> android: add the Android KUnit test

- automated/linux/torizon/ostree-upgrade-tests.sh
- automated/linux/torizon/ostree-upgrade-tests.yaml
Signed-off-by: Stevan Radaković <stevan.radakovic@linaro.org>
> laa: Add remote repository before fetching the latest image tag
